### ISSUE TITLE
`table_name` referenced before assigment when creating new datasource

### ISSUE THREAD

**Issue by dafeda** [fivetran/great_expectations#2834] opened 2021-05-26 08:13 UTC
**Describe the bug**
`context.test_yaml_config(yaml_config=example_yaml)` fails when trying to create a MSSQL datasource.

A similar error was reported in #support when trying to create a Redshift datasource:
https://greatexpectationstalk.slack.com/archives/CUTCNHN82/p1619537207408900

**To Reproduce**
1. Run command to create new datasource (Opens up Jupyter notebook):
`great_expectations --v3-api datasource new`

2. Use connection string suitable for SQL Server:
`connection_string = "mssql+pyodbc://@<SERVER URL>/<DATABASE NAME>?trusted_connection=yes&driver=ODBC Driver 
17 for SQL Server&charset=utf&autocommit=true"`

3. Run `context.test_yaml_config(yaml_config=example_yaml)`

Results in:

`DatasourceInitializationError: Cannot initialize datasource my_datasource, error: local variable 'table_name' referenced before assignment`

**Expected behavior**
Not sure what the output should look like, but it should not throw an error.

**Environment (please complete the following information):**
 - Windows 10 Enterprise
 - Great Expectations Version: [e.g. 0.13.19]

**Additional context**

I am pretty sure that the bug is due to the variable `table_name` being used before it's initialized in the code linked to below.

https://github.com/great-expectations/great_expectations/blob/635602c3c526b5b477220d410d10209fe689319f/great_expectations/datasource/data_connector/inferred_asset_sql_data_connector.py#L240-L257

`table_name` is defined in a for-loop above:

https://github.com/great-expectations/great_expectations/blob/635602c3c526b5b477220d410d10209fe689319f/great_expectations/datasource/data_connector/inferred_asset_sql_data_connector.py#L225-L230

**Comment by dafeda** [comment] 2021-06-11 17:53
I'm working on this.

https://github.com/great-expectations/great_expectations/pull/2898

**Comment by eugmandel** [comment] 2021-06-14 15:08
@dafeda Thank you for reporting this and working on the PR!

**Comment by dafeda** [comment] 2021-06-15 06:07
> @dafeda Thank you for reporting this and working on the PR!

My pleasure!
There are a few conceptual issues I would like to discuss, and have written a post about it in Slack.
Is Slack the best forum to discuss such things?

https://greatexpectationstalk.slack.com/archives/CV828B2UX/p1623435170031000

**Comment by Beetelbrox** [comment] 2021-07-17 10:04
Hello! I've hit the same issue as above when trying to use an InferredAssetSqlDataConnector, and by checking the code I believe that the issue is actually caused by a typo. If we check the code block with the for loop that fails (which happens to be untested):

https://github.com/great-expectations/great_expectations/blob/f88fab6cc32bc8f7ae76e51e6eb235ebc8a3a5d4/great_expectations/datasource/data_connector/inferred_asset_sql_data_connector.py#L240-L257

We can see how the loop is iterating over the views into the variable `view_name` and the same variable is later stored into the `tables` list, but the if condition is on `table_name`. Seems like a copy-paste issue.
This is further confirmed by the error not happening if we disable view inclusion in the config:
```
introspection:
  include_views: False
```
Hope this helps.

Have a great weekend!

**Comment by talagluck** [comment] 2021-07-27 17:20
Thank you @dafeda and thanks for the feedback @Beetelbrox ! I believe the bug itself has been resolved in PR #3069. That said, your additions to testing in #2898 look interesting. I'm going to close this issue, and follow up with you in the PR.

**Closed as completed by talagluck** 2021-07-27 17:20 UTC
