### ISSUE TITLE
Unable to create expectation suite with v3-api using a relational (postgres) datasource

### ISSUE THREAD

**Issue by mpalfi** [fivetran/great_expectations#3649] opened 2021-11-09 19:46 UTC
**Describe the bug**
When referencing a relational datasource (postgres or mysql) I am unable to create suite using v3-api via the CLI.
When running great_expectations --v3-api suite new, with option 3 (automatically, using a profiler) , referencing the datasource , providing a schema and table name that the user has access to I am getting the following error:

  File "C:\Users\xxxx\AppData\Roaming\Python\Python37\site-packages\great_expectations\datasource\data_connector\configured_asset_sql_data_connector.py", line 150, in get_batch_definition_list_from_batch_request
    sub_cache = self._data_references_cache[batch_request.data_asset_name]
KeyError: 'masterdata.w_resource_d'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python37\Scripts\great_expectations.exe\__main__.py", line 9, in <module>
  File "C:\Users\xxxx\AppData\Roaming\Python\Python37\site-packages\great_expectations\cli\cli.py", line 161, in main
    cli()
  File "C:\Users\xxxx\AppData\Roaming\Python\Python37\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python37\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python37\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\xxxx\AppData\Roaming\Python\Python37\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\xxxx\AppData\Roaming\Python\Python37\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python37\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python37\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python37\site-packages\great_expectations\cli\suite.py", line 138, in suite_new
    batch_request=batch_request,
  File "C:\Users\xxxx\AppData\Roaming\Python\Python37\site-packages\great_expectations\cli\suite.py", line 344, in _suite_new_workflow
    raise e
  File "C:\Users\xxxx\AppData\Roaming\Python\Python37\site-packages\great_expectations\cli\suite.py", line 326, in _suite_new_workflow
    assume_yes=False,
  File "C:\Users\xxxx\AppData\Roaming\Python\Python37\site-packages\great_expectations\cli\suite.py", line 690, in _suite_edit_workflow
    raise e
  File "C:\Users\xxxx\AppData\Roaming\Python\Python37\site-packages\great_expectations\cli\suite.py", line 634, in _suite_edit_workflow
    batch_request=batch_request,
  File "C:\Users\xxxx\AppData\Roaming\Python\Python37\site-packages\great_expectations\render\renderer\v3\suite_profile_notebook_renderer.py", line 27, in __init__
    expectation_suite_name=expectation_suite_name,
  File "C:\Users\xxxx\AppData\Roaming\Python\Python37\site-packages\great_expectations\data_context\data_context.py", line 1844, in get_validator
    **kwargs,
  File "C:\Users\xxxx\AppData\Roaming\Python\Python37\site-packages\great_expectations\data_context\data_context.py", line 1659, in get_batch_list
    batch_request=batch_request
  File "C:\Users\xxxx\AppData\Roaming\Python\Python37\site-packages\great_expectations\datasource\new_datasource.py", line 143, in get_batch_list_from_batch_request
    batch_request=batch_request
  File "C:\Users\xxxx\AppData\Roaming\Python\Python37\site-packages\great_expectations\datasource\data_connector\configured_asset_sql_data_connector.py", line 153, in get_batch_definition_list_from_batch_request
    f"data_asset_name {batch_request.data_asset_name} is not recognized."
KeyError: 'data_asset_name masterdata.w_resource_d is not recognized.'

**To Reproduce**
1. After prototyping successfully with v2-api I tried to do the same with v3-api and I created  a new project
2. Initialized with v3-api
3. created the datasource with great_expectations --v3-api datasource new
4. checked configuration: great_expectations --v3-api project check-config and got: Your config file appears valid!
5. when running great_expectations --v3-api suite new , I am using option 3, reference the datasource just created and getting the error referenced above
**Expected behavior**
Suite gets created, Jupyter notebook opens to follow through with the configuration.

**Environment (please complete the following information):**
 - Operating System: [Windows]
 - Great Expectations Version: [0.13.41]

**Additional context**

**Comment by talagluck** [comment] 2021-11-10 20:56
Hi @mpalfi - thanks for opening this issue! Could you please include the `BatchRequest` with which the notebook automatically populated? To confirm, you did not edit this at all?

**Comment by mpalfi** [comment] 2021-11-11 15:53
Here is the batch request that is generated when I try to edit the suite.

batch_request = {
    "datasource_name": "bdl_test_v3",
    "data_connector_name": "whole_table",
    "data_asset_name": "masterdata.w_resource_d",
    "limit": 1000,
}

Pasting also the datasource from the configuration file:
  bdl_test_v3:
    class_name: SimpleSqlalchemyDatasource
    introspection:
      whole_table:
        data_asset_name_suffix: __whole_table
    module_name: great_expectations.datasource
    credentials: ${bdl_test_v3}

I can confirm that I did not edit either, both are generated just by CLI actions.

**Comment by mpalfi** [comment] 2021-11-12 14:34
adding also below the result of  (context.test_yaml_config(yaml_config=example_yaml) when creating this datasource.
It seems slightly different from what I see in the documentation at : https://docs.greatexpectations.io/docs/guides/setup/configuring_data_contexts/how_to_configure_datacontext_components_using_test_yaml_config in the sense that does not return sample data. Not sure if this is relevant to the error received when trying to create suite:
________________________________________________
Attempting to instantiate class from config...
	Instantiating as a Datasource, since class_name is SimpleSqlalchemyDatasource
	Successfully instantiated SimpleSqlalchemyDatasource


ExecutionEngine class name: SqlAlchemyExecutionEngine
Data Connectors:
	whole_table : InferredAssetSqlDataConnector

	Available data_asset_names (3 of 18828):
		CI_STAGING_DATA__whole_table (1 of 1): [{}]
		Dts_svc_prfl__whole_table (1 of 1): [{}]
		Test_GP__whole_table (1 of 1): [{}]

	Unmatched data_references (0 of 0): []
<great_expectations.datasource.simple_sqlalchemy_datasource.SimpleSqlalchemyDatasource at 0x21f9700d748>

**Comment by cdkini** [comment] 2021-11-22 13:44
Hey @mpalfi! I believe the issue here is an existing bug we have around data asset naming in v3.  Currently, v3 doesn’t support `schema_name.table_name` in config. Instead, please use `schema name` and `batch_spec_passthrough` as a workaround.

```python
batch_request = {
    "datasource_name": "my_postgres_datasource",
    "data_connector_name": "default_inferred_data_connector_name",
    "data_asset_name": "my_table_name",
    "limit": 1000,
    "batch_spec_passthrough":{
        "schema_name": "my_schema_name"
    }
}
```

Here's a similar issue that might provide more context: https://github.com/great-expectations/great_expectations/issues/2936

**Comment by cdkini** [comment] 2021-11-23 13:04
As this is a duplicate of the issue I've noted above, I'm going to close down this issue. Hope the workaround helps for now! We've got a full fix in the works for the future.

**Closed as completed by cdkini** 2021-11-23 13:04 UTC
Labels: community, devrel
