### ISSUE TITLE
Spark context is stopped when creating BaseDataContext on databricks

### ISSUE THREAD

**Issue by alex-hsp** [fivetran/great_expectations#3367] opened 2021-09-08 07:57 UTC
**Describe the bug**
This is a reopen of #2561 because it still reproduce on the fresh GE version 0.13.32
I copypasted an example from docs https://docs.greatexpectations.io/docs/deployment_patterns/how_to_instantiate_a_data_context_on_databricks_spark_cluster/ and it stops spark context and thus crashes driver on databricks. 

![Снимок](https://user-images.githubusercontent.com/58466078/132468376-944d2ea0-a102-4ed3-be1d-44ee5224d6c4.PNG)

As you can see, a function developed to fix #2561 in #2587 is not working correctly.

**To Reproduce**
1. Start databricks cluster of 8.* runtime version
2. Install GE via `%pip install great_expectations`
3. Run an example https://docs.greatexpectations.io/docs/deployment_patterns/how_to_instantiate_a_data_context_on_databricks_spark_cluster/ (Configure a Data Context in code.)
4. `The spark context has stopped and the driver is restarting. Your notebook will be automatically reattached.`

**Expected behavior**
GE should not touchy spark context.

**Environment (please complete the following information):**
 - Operating System: Linux
 - Great Expectations Version: 0.13.32
 - Databricks runtime: 8.3
 - Spark: 3.1.1

**Additional context**
Is our prod code we rely on `DB_HOME` env var to determine if code is running under databricks or not. It is still running perfectly even across major databricks release (7.0 runtime -> 8.0)

**Comment by NathanFarmer** [comment] 2021-09-09 13:29
@alex-hsp Thank you for submitting this issue! Have you experienced this behavior using previous versions of GE and this is a regression or is this something you are experiencing for the first time? Also, is this something you are seeing in production code or is it only happening using the docs example?

**Comment by alex-hsp** [comment] 2021-09-09 14:14
No, i am first time user of GE. So far so good despite this bugster. I am getting used to GE and trying to figure out would it fit in our prod or not.

**Comment by anthonyburdi** [comment] 2021-11-01 21:11
Hi @alex-hsp - I was unable to replicate this issue using both GE v0.13.40 (latest) and v0.13.32 as you mentioned above (using databricks runtime v8.3). What output are you seeing from an `os.environ["DATABRICKS_RUNTIME_VERSION"]`?

**Comment by alex-hsp** [comment] 2021-11-02 08:42
@anthonyburdi it gives me a keyerror
This is os.environ.keys() on DBR 8.4
```
['CLASSPATH',
 'CLUSTER_DB_HOME',
 'DATABRICKS_ROOT_VIRTUALENV_ENV',
 'DB_HOME',
 'DRIVER_PID_FILE',
 'ENABLE_IPTABLES',
 'HIVE_HOME',
 'HOME',
 'HOSTNAME',
 'JAVA_HOME',
 'JAVA_OPTS',
 'KOALAS_USAGE_LOGGER',
 'LC_CTYPE',
 'MASTER',
 'MPLBACKEND',
 'OLDPWD',
 'PATH',
 'PIP_NO_INPUT',
 'PTY_LIB_FOLDER',
 'PWD',
 'PYSPARK_GATEWAY_PORT',
 'PYSPARK_GATEWAY_SECRET',
 'PYSPARK_PYTHON',
 'PYTHONHASHSEED',
 'PYTHONPATH',
 'PY_ACTIVATE',
 'R_LIBS',
 'SCALA_VERSION',
 'SHLVL',
 'SPARK_AUTH_SOCKET_TIMEOUT',
 'SPARK_BUFFER_SIZE',
 'SPARK_CONF_DIR',
 'SPARK_ENV_LOADED',
 'SPARK_HOME',
 'SPARK_LOCAL_DIRS',
 'SPARK_LOCAL_IP',
 'SPARK_PUBLIC_DNS',
 'SPARK_SCALA_VERSION',
 'SPARK_WORKER_MEMORY',
 'TERM',
 'USER',
 'VIRTUAL_ENV',
 '_']
```

**Comment by anthonyburdi** [comment] 2021-11-19 18:54
Thank you @alex-hsp - are you running Databricks using AWS, Azure or GCP?

**Comment by anthonyburdi** [comment] 2021-11-19 20:24
The reason I ask is that I am unable to replicate. I am running Databricks on AWS with v8.4 and the above works for me:
![image](https://user-images.githubusercontent.com/9903066/142687104-2dcb8d64-0aee-432d-b7a6-f5a5f780714d.png)

**Comment by alex-hsp** [comment] 2021-11-20 11:10
We are hosted on AWS
![Снимок](https://user-images.githubusercontent.com/58466078/142724095-6c935d7c-b891-47bc-a92b-2aa5da6e4308.JPG)
.

**Comment by paololucchino** [comment] 2022-05-18 08:28
I'm getting the same error from a different function call

Here is some code, my guess to what the issue is and how I am working around it. A proper solution would be better though! =)

ge version 0.15.5

![Screen Shot 2022-05-18 at 10 27 06 AM](https://user-images.githubusercontent.com/14344614/168994070-c18dc3f4-6c9f-4d54-a65a-adb077c59e81.png)

**Comment by AFineDayFor** [comment] 2022-08-10 16:08
This appears to be addressed in #3687. The updated documentation can be found [here](https://docs.greatexpectations.io/docs/deployment_patterns/how_to_use_great_expectations_in_databricks/) :smile:

Closing :bow:

Regarding @paololucchino 's remark, can you please create an indipdendent issue with context regarding your issue.

**Closed as completed by AFineDayFor** 2022-08-10 16:08 UTC
Labels: good first issue, community, devrel

**Comment by nathaneastwood** [comment] 2023-01-05 09:08
FWIW I am experiencing this exact same issue. I have copy-pasted [this](https://docs.greatexpectations.io/docs/deployment_patterns/how_to_use_great_expectations_in_databricks/) tutorial and it fails to run, therefore @AFineDayFor I don't believe that #3687 did address the problem. Setup info:

```
great-expectations: 0.15.41
DBR 10.4 LTS
Spark 3.2.1
```

I am running this within DataBricks itself in a notebook and AFAIK we are hosted on AWS. Similar to @alex-hsp I get a key error for `os.environ["DATABRICKS_RUNTIME_VERSION"]` and `in_databricks()` returns `False`.

**Comment by nathaneastwood** [comment] 2023-01-05 09:12
I just tried this on DBR 11.3 LTS and it worked. So the issue seems to be linked to DBR 10.4 LTS.
