### ISSUE TITLE
SuiteEditNotebookRenderer example does not work

### ISSUE THREAD

**Issue by rcwoolston** [fivetran/great_expectations#1966] opened 2020-10-06 11:12 UTC
**Describe the bug**
Attempted to use the edit suite notebook functionality by following the example hosted in the [docs](https://docs.greatexpectations.io/en/latest/guides/how_to_guides/configuring_generated_notebooks/how_to_configure_suite_edit_generated_notebooks.html). However, I receive the following error utilizing versions 0.12.1 and 0.12.3.

```bash
...
File "~/.conda/envs/great_expectations/lib/python3.8/site-packages/great_expectations/render/renderer/suite_edit_notebook_renderer.py", line 94, in from_data_context
    return instantiate_class_from_config(
  File "~/.conda/envs/great_expectations/lib/python3.8/site-packages/great_expectations/data_context/util.py", line 86, in instantiate_class_from_config
    raise TypeError(
TypeError: Couldn't instantiate class : SuiteEditNotebookRenderer with config : 
        custom_templates_module         notebook_assets.suite_edit
        header_markdown         None
        footer_markdown         None
        table_expectations_header_markdown              None
        column_expectations_header_markdown             None
        table_expectations_not_found_markdown           None
        column_expectations_not_found_markdown          None
        authoring_intro_markdown                None
        column_expectations_markdown            None
        header_code             None
        footer_code             <great_expectations.data_context.types.base.NotebookTemplateConfig object at 0x7f9645ed3d00>
        column_expectation_code         None
        table_expectation_code          None
 
expected str, bytes or os.PathLike object, not NoneType
```

Here is the relevant section from my great_expectations.yml
```
notebooks:
    suite_edit:
        custom_templates_module: notebook_assets.suite_edit
        footer_code:
            file_name: footer.py
            template_kwargs:
                site_name: site_local
                validation_operator_name: local
```

Here is my footer.py

```python
batch.save_expectation_suite(discard_failed_expectations=False)
run_id = {
    "run_name": "some_string_that_uniquely_identifies_this_run",  # insert your own run_name here
    "run_time": datetime.datetime.now(datetime.timezone.utc),
}
results = context.run_validation_operator(
    "{{ validation_operator_name }}", assets_to_validate=[batch], run_id=run_id
)
validation_result_identifier = results.list_validation_result_identifiers()[0]
context.build_data_docs(site_names=["{{ site_name }}"])
context.open_data_docs(validation_result_identifier, site_name="{{ site_name }}")
```

**To Reproduce**
Follow the steps from the [walkthrough ](https://docs.greatexpectations.io/en/latest/guides/how_to_guides/configuring_generated_notebooks/how_to_configure_suite_edit_generated_notebooks.html)using python 3.8 and great-expectations 0.12.1 or 0.12.3. 

**NOTE** I did not test any other versions, so they could also be problematic.

**Expected behavior**
Replace the footer code with the contents in footer.py

**Environment (please complete the following information):**
 - OS: Centos (Linux x86 64) 
- Python: 3.8
 - GE Version: 0.12.1, 0.12.3

**Additional context**
I am willing to contribute back to the docs and unittests, but I am unsure how to actually complete the action so I don't know what corrections need to be made.

**Comment by eugmandel** [comment] 2020-10-06 17:44
@rcwoolston I'll try to reproduce this locally and see if this is a bug. Will update.

**Comment by mbakunze** [comment] 2020-10-06 19:56
@rcwoolston - I think I ran into this as well. For notebook_assets.suite_edit location did you make sure there are `__init__.py` files so those are recognized as modules?

Check here: https://docs.greatexpectations.io/en/latest/reference/spare_parts/data_docs_reference.html?highlight=__init__.py#more-advanced-configuration

**Comment by rcwoolston** [comment] 2020-10-07 17:11
Good question, I do have an `__init__.py` in my suite_edit directory

![image](https://user-images.githubusercontent.com/5957841/95364035-8766bc00-088d-11eb-880d-8b702c4747bd.png)

**Comment by mbakunze** [comment] 2020-10-07 20:48
Also in notebook_assets? I am asking as I just checked our implementation and we have an 
`__init__.py` there as well and I think it did not work without.

**Comment by rcwoolston** [comment] 2020-10-08 03:21
That fixed it. I am trying to think what the default behavior is for initializing the project, I don't remember deleting any of those.

**Comment by eugmandel** [comment] 2020-12-01 00:09
Closing this issue, since there no code and docs fixes needed.

**Closed as completed by eugmandel** 2020-12-01 00:09 UTC
