### ISSUE TITLE
0.13.27 needs azure but does not declare the dep

### ISSUE THREAD

**Issue by alangenfeld** [fivetran/great_expectations#3239] opened 2021-08-12 22:02 UTC
**Describe the bug**
great_expectations/datasource/data_connector/util.py expects `azure` to be available but it is not declared in requirements.txt / setup.py

**To Reproduce**
1. pip install great-expectations
2. import great_expectations
3.
```
  | import great_expectations as ge
  | .tox/py38/lib/python3.8/site-packages/great_expectations/__init__.py:7: in <module>
  | from great_expectations.data_context import DataContext
  | .tox/py38/lib/python3.8/site-packages/great_expectations/data_context/__init__.py:1: in <module>
  | from .data_context import BaseDataContext, DataContext, ExplorerDataContext
  | .tox/py38/lib/python3.8/site-packages/great_expectations/data_context/data_context.py:41: in <module>
  | from great_expectations.core.usage_statistics.anonymizers.data_connector_anonymizer import (
  | .tox/py38/lib/python3.8/site-packages/great_expectations/core/usage_statistics/anonymizers/data_connector_anonymizer.py:2: in <module>
  | from great_expectations.datasource.data_connector import (
  | .tox/py38/lib/python3.8/site-packages/great_expectations/datasource/__init__.py:1: in <module>
  | from .data_connector.data_connector import DataConnector
  | .tox/py38/lib/python3.8/site-packages/great_expectations/datasource/data_connector/__init__.py:1: in <module>
  | from .configured_asset_file_path_data_connector import (
  | .tox/py38/lib/python3.8/site-packages/great_expectations/datasource/data_connector/configured_asset_file_path_data_connector.py:11: in <module>
  | from great_expectations.datasource.data_connector.file_path_data_connector import (
  | .tox/py38/lib/python3.8/site-packages/great_expectations/datasource/data_connector/file_path_data_connector.py:18: in <module>
  | from great_expectations.datasource.data_connector.util import (
  | .tox/py38/lib/python3.8/site-packages/great_expectations/datasource/data_connector/util.py:12: in <module>
  | from azure.core.paging import ItemPaged
  | E   ModuleNotFoundError: No module named 'azure'
```

**Expected behavior**
`azure` is installed via setup.py deps or `azure` import is conditional on use of `azure` related features 

**Environment (please complete the following information):**
 - Operating System: Linux
 - Great Expectations Version: 0.13.27

**Additional context**

**Comment by dataframing** [comment] 2021-08-13 06:46
+1, this seems to be caused by https://github.com/great-expectations/great_expectations/pull/3141.

Downgrading to 0.13.26 works as a temporary fix 👍🏻

**Comment by Glen-Pennington** [comment] 2021-08-13 13:20
We are experiencing this error with 0.13.26.

**Comment by fjork3** [comment] 2021-08-13 17:12
Thanks for the report! Being addressed by #3244 , we'll be pushing a new release and updating here as soon as possible.

**Comment by fjork3** [comment] 2021-08-13 22:09
This should be fixed in release `0.13.28`; can you confirm whether you're still seeing issues?

**Comment by Glen-Pennington** [comment] 2021-08-15 13:30
I will test on Monday, thanks for the quick turn around on the fix.

**Comment by Glen-Pennington** [comment] 2021-08-16 14:33
> This should be fixed in release `0.13.28`; can you confirm whether you're still seeing issues?

Release 0.13.28 resolved this issue for me, deployed and tested in Azure.

**Closed as completed** 2021-08-16 14:47 UTC
Labels: community
