### ISSUE TITLE
[BUG] Expectations duplicate after a few runs

### ISSUE THREAD

**Issue by adam-mrozik** [fivetran/great_expectations#6111] opened 2022-09-29 13:38 UTC
**Describe the bug**
Hey Guys,

I am running my expectations for Clickhouse datasource and after a couple of runs, for no reason whatsoever, Great Expectations decide to multiply every NOT NULL expectation I have by the factor of 3, which causes SQL query to fail.

First few runs (correct):
![image](https://user-images.githubusercontent.com/92296835/193047051-4193a35e-ee00-4284-b1d5-8b7ba41daeef.png)

Next runs (incorrect, rules count increased):
![image](https://user-images.githubusercontent.com/92296835/193047123-4c4f4619-6a9f-4cc1-be14-88311f499341.png)

Incorrect report (multiplication happens for every not null check)
![image](https://user-images.githubusercontent.com/92296835/193046346-5aed2a31-9f08-4d3b-a15e-71a53fb23d9b.png)

**Expected behavior**
Great Expectations should not multiply my written rules for no reason

**Environment (please complete the following information):**
 - Operating System: Docker Ubuntu Container
 - Great Expectations Version: 0.15.25

**Comment by austiezr** [comment] 2022-09-30 16:58
Hey @adam-mrozik ! Thanks for raising this. Are you able to share some details around your configs & workflow generating this behavior (with any PII removed)? That will help us to better investigate what may be happening here.

**Comment by adam-mrozik** [comment] 2022-10-03 09:05
Sure!

clickhouse_event.json expectations (part of it, they are mostly just expect not to be null + one mean check, 41 checks overall)
```
{
    "data_asset_type": null,
    "expectation_suite_name": "clickhouse_event",
    "expectations": [
        {
            "expectation_type": "expect_column_mean_to_be_between",
            "kwargs": {
                "min_value": 0.2,
                "max_value": 0.6,
                "column": "column10"
            },
            "meta": {}
        },
        {
            "expectation_type": "expect_column_values_to_not_be_null",
            "kwargs": {
                "column": "column6"
            },
            "meta": {}
        },
        {
            "expectation_type": "expect_column_values_to_not_be_null",
            "kwargs": {
                "column": "column1"
            },
            "meta": {}
        },
        {
            "expectation_type": "expect_column_values_to_not_be_null",
            "kwargs": {
                "column": "column2"
            },
            "meta": {}
        },
        {
            "expectation_type": "expect_column_values_to_not_be_null",
            "kwargs": {
                "mostly": 0.25,
                "column": "column3"
            },
            "meta": {}
        },
        {
            "expectation_type": "expect_column_values_to_not_be_null",
            "kwargs": {
                "mostly": 0.25,
                "column": "column4"
            },
            "meta": {}
        },
```

great_expectations file:
```
config_version: 3.0

  # Datasources tell Great Expectations where your data lives and how to get it.
  # You can use the CLI command `great_expectations datasource new` to help you
  # add a new datasource. Read more at https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/connect_to_data_overview
datasources:
  clickhouse_source:
    execution_engine:
      connection_string: clickhouse+native://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      module_name: great_expectations.execution_engine
      class_name: SqlAlchemyExecutionEngine
    data_connectors:
      default_runtime_data_connector_name:
        name: default_runtime_data_connector_name
        module_name: great_expectations.datasource.data_connector
        batch_identifiers:
          - default_identifier_name
        class_name: RuntimeDataConnector
      default_inferred_data_connector_name:
        name: default_inferred_data_connector_name
        include_schema_name: true
        module_name: great_expectations.datasource.data_connector
        class_name: InferredAssetSqlDataConnector
    module_name: great_expectations.datasource
    class_name: Datasource
config_variables_file_path: uncommitted/config_variables.yml

  # The plugins_directory will be added to your python path for custom modules
  # used to override and extend Great Expectations.
plugins_directory: plugins/

stores:
  # Stores are configurable places to store things like Expectations, Validations
  # Data Docs, and more. These are for advanced users only - most users can simply
  # leave this section alone.
  #
  # Three stores are required: expectations, validations, and
  # evaluation_parameters, and must exist with a valid store entry. Additional
  # stores can be configured for uses such as data_docs, etc.
  expectations_store:
    class_name: ExpectationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: expectations/

  validations_store:
    class_name: ValidationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/validations/

  evaluation_parameter_store:
    class_name: EvaluationParameterStore
  checkpoint_store:
    class_name: CheckpointStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: checkpoints/

  profiler_store:
    class_name: ProfilerStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: profilers/

expectations_store_name: expectations_store
validations_store_name: validations_store
evaluation_parameter_store_name: evaluation_parameter_store
checkpoint_store_name: checkpoint_store

data_docs_sites:
    # Data Docs make it simple to visualize data quality in your project. These
    # include Expectations, Validations & Profiles. The are built for all
    # Datasources from JSON artifacts in the local repo including validations &
    # profiles from the uncommitted directory. Read more at https://docs.greatexpectations.io/docs/terms/data_docs
  local_site:
    class_name: SiteBuilder
    show_how_to_buttons: true
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/data_docs/local_site/
    site_index_builder:
      class_name: DefaultSiteIndexBuilder
  s3_site:
    class_name: SiteBuilder
    store_backend:
      class_name: TupleS3StoreBackend
      bucket: ${DATA_QUALITY_BUCKET_NAME}
    site_index_builder:
      class_name: DefaultSiteIndexBuilder
      show_cta_footer: true
anonymous_usage_statistics:
  enabled: true
  data_context_id: fba52fb7-dd96-4126-a160-76332927b887
include_rendered_content:
  expectation_validation_result: false
  expectation_suite: false
  globally: false
notebooks:
```

Checkpoint being run:
```
name: global_checkpoint
config_version: 1.0
template_name:
module_name: great_expectations.checkpoint
class_name: Checkpoint
run_name_template:
expectation_suite_name:
batch_request: {}
action_list:
  - name: store_validation_result
    action:
      class_name: StoreValidationResultAction
  - name: store_evaluation_params
    action:
      class_name: StoreEvaluationParametersAction
  - name: update_data_docs
    action:
      class_name: UpdateDataDocsAction
      site_names: []
  - name: send_slack_notification_on_validation_result # name can be set to any value
    action:
      class_name: SlackNotificationAction
      # put the actual webhook URL in the uncommitted/config_variables.yml file or as env var
      slack_webhook: ${SLACK_URI}
      notify_on: failure # possible values: "all", "failure", "success"
      notify_with:
        - s3_site
      renderer:
        module_name: great_expectations.render.renderer.slack_renderer
        class_name: SlackRenderer
evaluation_parameters: {}
runtime_configuration: {}
validations:
  - batch_request:
      datasource_name: clickhouse_source
      data_connector_name: default_runtime_data_connector_name
      data_asset_name: ${DB_NAME}.my_table
    expectation_suite_name: clickhouse_event
profilers: []
ge_cloud_id:
expectation_suite_ge_cloud_id:
```


Checkpoint is just being run on a CronJob with Python. `query` is just a custom SQL, which selects the given columns (not sure if it is relevant for sharing):
```
run_name = f"{checkpoint_name}_quality_check_{now_str}"
    context.run_checkpoint(
        checkpoint_name=checkpoint_name,
        run_name=run_name,
        batch_request={
            "runtime_parameters": {"query": f"({query})"},
            "batch_spec_passthrough": {"create_temp_table": False},
            "batch_identifiers": {"default_identifier_name": run_name},
        },
    )
```



I have no immediate idea why is it happening. Could it be some kind of caching?

**Comment by talagluck** [comment] 2023-03-12 13:56
Hi @adam-mrozik - thanks again for raising this. GX doesn't offer full support for Clickhouse, and is not at all tested for Clickhouse. I'm not sure what might be causing this - I have never seen this issue before on any other backend. We're going to close this issue for now since it is happening with an unsupported backend and we have no way of reproducing; that said, if you are able to run a debugger to provide us with some more information about what might be happening, please feel free to re-open and we will take a look when we can.

**Closed as not planned by talagluck** 2023-03-12 13:56 UTC
Labels: community, feature:new_backend
