### ISSUE TITLE
Getting KeyError 'table.head' repeatedly when running validator.head() using runtime spark dataframe

### ISSUE THREAD

**Issue by mramakrishnan12** [fivetran/great_expectations#5478] opened 2022-07-11 02:00 UTC
**Describe the bug**
Continuously getting KeyError when running validator.head(5)

    860 for metric_configuration in metrics.values():
    861     logger.warning(f"Printing metric_configuration {metric_configuration}") 
    863 return {
    864     metric_configuration.metric_name: resolved_metrics[metric_configuration.id]
    865     for metric_configuration in metrics.values()
    866 }

    KeyError: ('table.head', 'batch_id=574f509507d4b19632b35f50cc8a275f', '04166707abe073177c1dd922d3584468')

**To Reproduce**
Below is my data source

    datasources={
            "name": "test_spark_df",
            "class_name":"Datasource",
            "module_name":"great_expectations.datasource",
            "execution_engine":{
                "class_name": "SparkDFExecutionEngine",
                "module_name": "great_expectations.execution_engine",
            },
            "data_connectors":{
                "default_runtime_data_connector_name": {
                    "class_name": "RuntimeDataConnector",
                    "module_name": "great_expectations.datasource.data_connector",
                    "batch_identifiers":  ["batch_id"],
                }
            },
    }

![image](https://user-images.githubusercontent.com/104850412/178174154-93f77b60-ea9b-40dd-b0d3-1948102e6af5.png)

    df=spark.read.csv('****/provider.csv',header='true')
    df.show(5)

    batch_request_pass = RuntimeBatchRequest(
    datasource_name="test_spark_df_2",
    data_connector_name="default_runtime_data_connector_name",
    data_asset_name="df",
    batch_identifiers={"batch_id": "df"},
    runtime_parameters={"batch_data": df},  
)

    context.create_expectation_suite(
    expectation_suite_name="test_suite", overwrite_existing=True)

    validator = context.get_validator(
    batch_request=batch_request_pass, expectation_suite_name="test_suite")

    validator.head()

    KeyError: ('table.head', 'batch_id=574f509507d4b19632b35f50cc8a275f', '04166707abe073177c1dd922d3584468')

**Expected behavior**
Expected to the first few rows from the spark dataframe

**Environment (please complete the following information):**
 - Linux
 - Great Expectations, version 0.15.11

**Additional context**

**Comment by rdodev** [comment] 2023-03-09 19:15
Hey @mramakrishnan12 if you remove the line `validator.head()` the issue should go away.

**Comment by alexsherstinsky** [comment] 2023-06-06 18:19
@mramakrishnan12 Thank you very much for reporting this issue.  Much has changed since you first reported it (almost a year has passed), and right now the connecting to data API in GX has been significantly improved, making it easier than ever before to do so (using the new "Fluent Datasources" approach).  Would it be possible for you to rerun your test case and let us know whether or not the error you have observed still occurs?  In the later case, the full code with data for us to be able to reproduce would be greatly appreciated.  Thank you -- and thank you for using Great Expectations!

**Comment by alexsherstinsky** [comment] 2023-06-15 23:53
@mramakrishnan12 I am closing this issue for now. Please feel free to reopen and let us know at any time.

**Closed as completed by alexsherstinsky** 2023-06-15 23:53 UTC
Labels: triage
