### ISSUE TITLE
Great Expectations long execution time in GCP

### ISSUE THREAD

**Issue by ibudincevicbol** [fivetran/great_expectations#3620] opened 2021-11-01 13:34 UTC
**Describe the bug**
Very long execution times (30-45 minutes) for Great Expectations in our GCP PRO environment only, but it runs fast (30 seconds) on our STG environment.

**To Reproduce**
1. Run Great Expectations in python through 'context.run_checkpoint' with a GCP storage bucket as StoreValidationResultAction and UpdateDataDocsAction location. 
2. On our STG environment this step takes around 30 seconds, while on PRO it takes > 30 minutes. 
3. The output docs and validation files seem to already be present on the bucket after around 30 seconds even on PRO, but the job is stuck on the 'context.run_checkpoint' step for 30 minutes with no output in the logs. 
4. An example log output showing the difference with STG and PRO: 

```log
STG
[2021-10-29 06:13:15,283] Executing the great expectation validations for checkpoint: v3_failures_checkpoint.
[2021-10-29 06:13:15,583] g
[great_expectations_yml.txt](https://github.com/great-expectations/great_expectations/files/7453571/great_expectations_yml.txt)
[v3_failures_checkpoint_yml.txt](https://github.com/great-expectations/great_expectations/files/7453572/v3_failures_checkpoint_yml.txt)
reat_expectations.validator.validator - \t2 expectation(s) included in expectation_suite.
[2021-10-29 06:13:40,293] \rCalculating Metrics:   0%|          | 0/4 [00:00<?, ?it/s]\rCalculating Metrics: 100%|\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88| 4/4 [00:00<00:00, 634.20it/s]
[2021-10-29 06:13:40,294] Finished validations with run_id: airflow__scheduled__2021-10-29T05:10:00+00:00

PRO
[2021-10-29 06:28:29,059] Executing the great expectation validations for checkpoint: v3_failures_checkpoint.
[2021-10-29 06:28:29,359] great_expectations.validator.validator - \t2 expectation(s) included in expectation_suite.
[2021-10-29 06:58:48,839] \rCalculating Metrics:   0%|          | 0/4 [00:00<?, ?it/s]\rCalculating Metrics: 100%|\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88| 4/4 [00:00<00:00, 634.20it/s]
[2021-10-29 06:58:48,840] Finished validations with run_id: airflow__scheduled__2021-10-29T05:10:00+00:00
```

**Expected behavior**
We expect the duration of the checkpoint to be roughly similar between STG and PRO, with perhaps a bit longer running time on PRO due to more data, but not in the order of 30 minutes.

**Environment (please complete the following information):**
 - Kubernetes Pod running in our company GCP cluster on the https://cloud.google.com/kubernetes-engine/ . The Pod is triggered using Airflow. The pod runs a Docker image, which contains our python scripts which execute the Great Expectations suite by using a checkpoint. 
 - Perhaps also relevant is that our company uses Istio sidecars to mediate in communication across different Kubernetes pods. We use the company default Istio settings which have so far not caused any communication issues with writing to GCP storage.
 - The output of the Great Expectations is sent to a GCP storage bucket in a different GCP project, but all of the permissions are properly setup.
 - Configuration files for reference: 
 
[great_expectations_yml.txt](https://github.com/great-expectations/great_expectations/files/7453579/great_expectations_yml.txt)

[v3_failures_checkpoint_yml.txt](https://github.com/great-expectations/great_expectations/files/7453580/v3_failures_checkpoint_yml.txt)
 
 - There should be no obvious difference between the STG and PRO clusters, as far as we are aware.
 - Great Expectations Version: [e.g. 0.13.37]

**Additional context**
 We are using GE 0.13.37 with checkpoints with the V3 API. We run GE from inside a Kubernetes pod which is run in a Google Cloud environment, and the pod is triggered from Airflow. We have both a STG and PRO environment, which are run in different clusters. On the STG environment the GE step takes around 30 seconds to complete, but on the PRO environment it takes around 30 minutes. We suspect it is some timeout/communication issue.  As mentioned the job is running on a Kubernetes pod and it is publishing this output to a GCP storage bucket. We have seen that the output GE docs validation html file is created on PRO also after around 30 seconds, but our job hangs for 30 minutes on the execution of the checkpoint, even though it seems like the files have already been uploaded. The size of the data should not be an issue, as we use pandas validation on a .pkl file which is usually around 200 MB in size.

**Comment by talagluck** [comment] 2021-11-03 18:46
Thanks for opening this issue, @ibudincevicbol! That definitely sounds like an issue, and someone on the team will take a look and get back soon. To clarify in the meantime, what is STG?

I also wanted to point you to some multi-threading functionality introduced with #3362 . This is currently experimental, but it would be good to hear if this is helpful for you.

**Comment by ibudincevicbol** [comment] 2021-11-04 10:06
Hello, thank you for taking a look! Sorry for the confusion, STG=staging, so that is our staging environment where we test our services before deploying to the PRO=production environment in the GCP. As mentioned in the ticket, I asked our infrastructure team (we are more of a data science/development team) and they said there should be no difference expected between the two clusters in terms of performance. Thank you also for the multi-threading link, I will take a look at it and see if it could be applicable to our situation.

**Comment by ibudincevicbol** [comment] 2021-11-08 08:04
Perhaps this is related to the issue, but sometimes the validation step also fails with an internal error as seen in the logs bellow. Note this could also be Istio catching  an error, as all of our jobs are run through a scuttle wrapper which enables Istio to handle all communication from the kubernetes pod, which is done for all of our company's cloud jobs . 

```
[2021-11-06 20:58:41,350] {pod_launcher.py:125} INFO - b'\rCalculating Metrics:   0%|          | 0/125 [00:00<?, ?it/s]\rCalculating Metrics:  37%|\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x8b      | 46/125 [00:13<00:22,  3.44it/s]/usr/local/lib/python3.8/site-packages/great_expectations/expectations/metrics/column_map_metrics/column_value_lengths.py:115: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.\n'
[2021-11-06 20:58:41,351] {pod_launcher.py:125} INFO - b'  metric_series = column_lengths.between(\n'
[2021-11-06 21:12:59,380] {pod_launcher.py:125} INFO - b"scuttle: Stopping Istio using Istio API 'http://127.0.0.1:15020' (intended for Istio >v1.2)\n"
[2021-11-06 21:12:59,384] {pod_launcher.py:125} INFO - b'\rCalculating Metrics:  91%|\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88 | 114/125 [00:17<00:01,  7.25it/s]\rCalculating Metrics: 100%|\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88| 125/125 [00:18<00:00,  7.54it/s]\rCalculating Metrics: 100%|\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88| 125/125 [00:18<00:00,  6.59it/s]panic: runtime error: invalid memory address or nil pointer dereference\n'
[2021-11-06 21:12:59,385] {pod_launcher.py:125} INFO - b'[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7ca9a7]\n'
[2021-11-06 21:12:59,385] {pod_launcher.py:125} INFO - b'\n'
[2021-11-06 21:12:59,385] {pod_launcher.py:125} INFO - b'goroutine 1 [running]:\n'
[2021-11-06 21:12:59,385] {pod_launcher.py:125} INFO - b'main.killIstioWithAPI()\n'
[2021-11-06 21:12:59,385] {pod_launcher.py:125} INFO - b'\t/Users/btoonk/repo/scuttle/main.go:134 +0x287\n'
[2021-11-06 21:12:59,386] {pod_launcher.py:125} INFO - b'main.kill(0xffffffffffffffff)\n'
[2021-11-06 21:12:59,386] {pod_launcher.py:125} INFO - b'\t/Users/btoonk/repo/scuttle/main.go:109 +0xcc\n'
[2021-11-06 21:12:59,386] {pod_launcher.py:125} INFO - b'main.main()\n'
[2021-11-06 21:12:59,386] {pod_launcher.py:125} INFO - b'\t/Users/btoonk/repo/scuttle/main.go:83 +0x31f\n'
```

**Comment by ibudincevicbol** [comment] 2021-11-09 12:17
> Thanks for opening this issue, @ibudincevicbol! That definitely sounds like an issue, and someone on the team will take a look and get back soon. To clarify in the meantime, what is STG?
> 
> I also wanted to point you to some multi-threading functionality introduced with #3362 . This is currently experimental, but it would be good to hear if this is helpful for you.

I tried enabling this multithredding option by setting 
`context.get_config(mode='typed').concurrency._enabled = True` but I did not see an improvement in speed. Additionally the pod metrics indicated that it was still using 1 CPU while there were 2 available. Perhaps this is not the correct way to enable it? I couldn't find a more detailed way of how to enable this feature in the link provided nor the docs.

**Comment by ibudincevicbol** [comment] 2021-11-09 12:22
We perhaps have some more idea on why there is such a drastic difference in processing time between the two environments. We believe it has to do with the size of the 'data_docs/index.html' file. Our job runs once every hour and each hour has it's own set of 2 validation runs based on 2 expectation suites, one for warning validations and one for failure validations. This means that we are creating some 48 runs per day, which are all added to the index.html file by Great Expectations. On STG we were not running that long with the expectations as we did not have a PRO-like setup earlier, so the index.html file on STG was fairly small < 1 MB. On PRO however, the history has accumulated since around April 2021 and the data_docs/index.html file is ~ 17 MB. We believe this is the reason why the validation data docs step lasts so long on our PRO environment, but this needs to be fixed internally in Great Expectations in order to be able to handle a larger history.

**Comment by talagluck** [comment] 2021-11-09 14:07
Hi @ibudincevicbol, thank you for following up here.

We are currently aware of the bottleneck with rendering data docs with large numbers of validations, and it makes sense that this could be the main source of the difference between your two environments. This is something that we are looking into, though it may take us some time to get to the bottom of the issue. In the meantime, there is a workaround for this by limiting the number of validation results render. [You can see some more information about this here.](https://discuss.greatexpectations.io/t/what-does-the-validation-results-limit-option-in-data-docs-limit/310).

re: concurrency: I'm surprised that you had to set this using the "private" variable, as I would have thought you could set it directly with `context.concurrency.enabled = True`. That said, the `concurrency` feature has a somewhat limited scope, in that it will only multithread if you have multiple validations on a checkpoint. It also won't currently help with the DataDocs rendering, so if that is the main source of slowness, then this wouldn't be the right solution.

As far as the validation step failing with an internal error, this looks like it may be related specifically to your environment, and would be tough for us to replicate, but please let me know if you have any ideas as to the contrary.

If the main source of the issue here is DataDocs rendering (and I wouldn't be surprised if it is), then I believe this is a duplicate of #3396, and not specific to GCP. Let me know if you agree, and I'll close this issue, though again, we are looking into speeding up data docs rendering with many validations, and I really appreciate the feedback you've provided here.

**Comment by ibudincevicbol** [comment] 2021-11-09 14:43
hi, thank you for your reply and suggestions. Concerning the multithredding, I tried doing `context.concurrency.enabled = True` , but received an error something like 'cannot set attributes'. In any case yes it seems that will not fix our current issue.
Thank you for the suggestion for the workaround, but we decided already to temporarily pause the docs output to GCS until this is resolved in the library itself. The workaround does not seem like a permanent solution to us, so in the interest of our roadmap we will move on to more pressing matters, while waiting for a general fix. 
Today we tested our job with only publishing docs to local_site instead of to GCP storage and the job took 2 minutes instead of 30, so for us the long duration time is definitely only related to that rendering issue, so not GCP specific. In that case I believe you are free to close this ticket, and please let us/me know when the issue has been resolved properly.

**Comment by talagluck** [comment] 2021-11-10 14:25
Sounds good - thanks so much for letting me know, @ibudincevicbol. I know you can actually specify your `concurrency` config within your `DataContext` config, but I would need to do some digging to get the details.

Either way, we will close this issue for now, and let you know as we resolve the issue with rendering. Thanks again for your follow-up here.

**Closed as completed by talagluck** 2021-11-10 14:25 UTC
Labels: community, devrel
