### ISSUE TITLE
Trailing comma in expectation json causes hard to debug json parse error. 

### ISSUE THREAD

**Issue by samLozier** [fivetran/great_expectations#4060] opened 2022-01-25 19:57 UTC
**Describe the bug**
If an expectation.json is manually edited in such a way that a trailing comma is left in the expectations array, the parser adds "null" to the end of the array which triggers difficult to debug json parse errors. 

**To Reproduce**
1. Create an expectation
2. Manually edit the list of expectations:
```
  "expectations": [
    {
      "expectation_type": "expect_table_columns_to_match_ordered_list",
     .... # additional fields dropped for clarity
    },  # note trailing comma
]
```
the parser views this as 
```
  "expectations": [
    {
      "expectation_type": "expect_table_columns_to_match_ordered_list",

    }, 
    null
]
```

3. Run a checkpoint containing this expectations
4. See error and try to figure out where it came from. 

**Expected behavior**
Either a more verbose error that calls out which expectation generated the error as well as a proposed fix, or a a modification to the parser that drops nulls from arrays. 

**Environment (please complete the following information):**
 - Operating System: macos
 - Great Expectations Version: [e.g. 0.14.0]

**Additional context**
expectation has been created and run with the v3 api

**Comment by joshua-stauffer** [comment] 2022-01-26 18:00
Hi @samLozier, thanks for raising this issue! one clarifying question: when you say 'manually edit the list of expectations', I understand that you alter the expectation json file by hand. Is this correct, or does this happen when you alter the expectation programmatically as well?

**Comment by samLozier** [comment] 2022-01-26 20:36
@joshua-stauffer Your understanding was correct. I thought I'd save myself time by directly editing the json file by hand since I was trying to remove a single expectation. 

So far it has not happened to me when editing programmatically

**Comment by jcampbell** [comment] 2022-01-27 14:04
@samLozier  -- I can't replicate this. Here's the snippet I'm using...

```
import pandas as pd
import uuid

from great_expectations.checkpoint import Checkpoint
from great_expectations.core import ExpectationConfiguration
from great_expectations.core.batch import BatchRequest, RuntimeBatchRequest
from great_expectations.data_context import BaseDataContext
from great_expectations.data_context.types.base import (
    ExecutionEngineConfig, DatasourceConfig, DataContextConfig,
    FilesystemStoreBackendDefaults, DataConnectorConfig,
)


df = pd.DataFrame({"foo": [1,2,3]})

config = DataContextConfig(
    datasources={
        "pandas": DatasourceConfig(
            class_name="Datasource",
            execution_engine=ExecutionEngineConfig(class_name="PandasExecutionEngine"),
            data_connectors={
                "runtime": DataConnectorConfig(class_name="RuntimeDataConnector", batch_identifiers=["id"])
            }
        )
    },
    store_backend_defaults=FilesystemStoreBackendDefaults(root_directory="/opt/replication/devrel/20220127/"),
)
context = BaseDataContext(project_config=config)
suite = context.create_expectation_suite("test_suite", overwrite_existing=True)
suite.add_expectation(
    ExpectationConfiguration(
        expectation_type="expect_column_to_exist",
        kwargs={
            "column": "foo"
        }
    )
)
context.save_expectation_suite(suite)

## manually edit the file, adding a comma after expectations

# Note that loading directly here *does* fail.
# However, the user reported the issue only in a checkpoint run, so I'm going to proceed with this commented and try a specific checkpoint
# suite = context.get_expectation_suite("test_suite")

checkpoint = Checkpoint(
    data_context=context,
    name="demo",
    config_version=1,
    run_name_template="Replication-%Y%m%d %H:%M:%S",
    validations=[{
        "expectation_suite_name": "test_suite",
        "action_list": [{
            "name": "store_validation_result",
            "action": {"class_name": "StoreValidationResultAction"}
        }]
    }]
)

checkpoint.run(
    batch_request=RuntimeBatchRequest(
        datasource_name="pandas",
        data_connector_name="runtime",
        data_asset_name="replication",
        batch_identifiers={"id": uuid.uuid4()},
        runtime_parameters={
            "batch_data": df
        }
    )
)

print("breakpoint")
```

**Comment by jcampbell** [comment] 2022-01-27 14:05
The attempt to run the checkpoint here also fails (correctly) with a `JSONDecodeError`

**Comment by samLozier** [comment] 2022-01-27 20:14
@jcampbell I just want to clarify a bit. It sounds like you were able to reproduce the behavior but I may not have been clear about exactly what I was trying to point out in the initial issue.

> The attempt to run the checkpoint here also fails (correctly) with a JSONDecodeError

My point was more of a DX comment. From the perspective of a fairly technical person new to GE and using the cli commands, the error was difficult to find. I had to switch to python execution and use the debugger to figure out what was going on. I'm in the process of rolling out this tool to the rest of my analyst team, and they would not have been able to dig in that far to solve the issue. My checkpoint has ~50 validations,  so I was hoping for something more direct in the cli. EG: "error parsing expectation: {name}, check that the json is valid" or something like that.

**Comment by jcampbell** [comment] 2022-01-28 02:43
Thanks for helping me understand a little better. I actually wasn't able to reproduce the error of adding the null expectation to the list, because I only observed the json decode error. To make sure I understand, how are you running the checkpoint that is giving you the extra null?

**Comment by joshua-stauffer** [comment] 2022-03-03 17:32
Hi @samLozier, thanks again for raising this -- I'm going to close the issue for now, but feel free to reopen if you continue running into this.

**Closed as completed by joshua-stauffer** 2022-03-03 17:32 UTC
Labels: triage, community
