### ISSUE TITLE
How can I configure a impala /hive data source?

### ISSUE THREAD

**Issue by l00173745** [fivetran/great_expectations#2321] opened 2021-01-25 14:53 UTC
I would like to check the data which extract by impala sql and maybe can be transfer into pandas dataframe , but no idea how to use in GE.

**Comment by eugmandel** [comment] 2021-02-01 22:44
@l00173745 We don't have documentation for Impala. Since this is not a bug/enhancement report, I am closing this issue, but you can ask this question on our Discuss forum, in case any users connected Great Expectations to Impala: https://discuss.greatexpectations.io/

**Closed as completed by eugmandel** 2021-02-01 22:44 UTC

**Comment by senri404** [comment] 2023-07-20 10:01
@l00173745 
Hello! Have you figured it out? I have such difficulty at this moment with Impala.

**Comment by DrewRoby** [comment] 2023-08-22 21:22
@senri404 
You can make a connection outside of the formal GX datasource framework, pull your data into a Pandas df, and move forward from there. e.g. for a Kerberized environment
```
from impala import dbapi
import pandas as pd
import great_expectations as gx

connection = dbapi.connect(host = "my-impala-instance.network.com', port = "20150", user = "my_user", auth_mechanism = "GSSAPI", use_ssl = True, kerberos_service_name = 'impala')
my_query = "select * from my_db.my_table limit 100"

df = pd.read_sql(sql=my_query, con=connection)
df_gx = gx.from_pandas(df)
```
and you're off to the races.  Not pretty, not perfect, but functional :)
As for how to get it working with the rest of the GX toolset... still working on that myself.
Hope that helps!

**Comment by senri404** [comment] 2023-08-26 18:35
@DrewRoby
Thank you for answering! But I wanted to connect directly to Impala datasource without using pandas. Pandas with really big data tables is too slow for my cases. If you are interested I figured out that you can connect to Impala (and I think to any datasource) with sqlalchemy.

**Comment by shwangdev** [comment] 2025-01-22 14:17
Any Update for this case?

**Comment by senri404** [comment] 2025-03-01 07:41
> Any Update for this case?

Hello!
I've found only one working method - using sqlalchemy.
