### ISSUE TITLE
[BUG] params_with_json_schema is undefined in _prescriptive_renderer method of ExpectCompoundColumnsToBeUnique

### ISSUE THREAD

**Issue by klatifch** [fivetran/great_expectations#5938] opened 2022-09-06 18:21 UTC
`params_with_json_schema` object is not declared in `_prescriptive_renderer` method in class `ExpectCompoundColumnsToBeUnique`. So if an expectation suite uses `expect_compound_columns_to_be_unique` with `mostly` param < 1.0, it causes `NameError: name 'params_with_json_schema' is not defined`

https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/expectations/core/expect_compound_columns_to_be_unique.py#L173

**Environment:**
 - Great Expectations Version: 0.15.19

[sample code and exp suite.zip](https://github.com/great-expectations/great_expectations/files/9499724/sample.code.and.exp.suite.zip)

**Comment by rdodev** [comment] 2022-09-08 15:42
Hey @klatifch thanks for the raising this issue. We'll take a look and report back.

**Comment by rdodev** [comment] 2022-09-08 19:04
Hey so this definitely looks like a bug, will chat with engineering about it.

**Comment by rdodev** [comment] 2022-09-09 12:20
Hey @klatifch a minor patch was just merged to address this issue. It should go out in next week's release. Please feel free to reopen this if the issue isn't resolved by next Friday (09/16/22).

**Closed as completed by rdodev** 2022-09-09 12:20 UTC
Labels: devrel
