### ISSUE TITLE
Quantiles not taking into account the number sign.

### ISSUE THREAD

**Issue by kuhnen** [fivetran/great_expectations#3180] opened 2021-08-05 05:39 UTC
**Describe the bug**
 Looks like the quantile profiling is taking into account absolute values for Min and Max.  Please take a look in the picture:
![image (2)](https://user-images.githubusercontent.com/1311776/128296822-864c409c-ce66-409d-b858-a83c09d6cadb.png)

**To Reproduce**
Create a dataset if some field to profile the data and have an expectation where the quantile has only negative values.

**Expected behavior**
Take a look in the picture.
-71 < -72
and it should be
-72 < -71

**Environment (please complete the following information):**
  Any environment.
**Additional context**
  We are using Athena.  

Thanks a lot.

**Comment by talagluck** [comment] 2021-08-05 19:53
Thanks for filing this issue, @kuhnen! We will review this internally and be in touch over the next several days.

**Comment by austiezr** [comment] 2021-11-17 19:55
Hey @kuhnen! Taking a look at this now and haven't been able to reproduce; are you able to verify that this is still an issue for you, and if so, provide an example of how you initially set up this expectation? That extra context may help diagnose what's happening here.

**Comment by kuhnen** [comment] 2021-11-18 15:38
@austiezr we still have the issue, I will take a deeper look to try to better understand,  thanks a lot for looking into this.
![image](https://user-images.githubusercontent.com/1311776/142446802-5c21ca07-afb8-4982-ae6d-5abd85b796fe.png)

**Comment by austiezr** [comment] 2021-11-22 19:59
@kuhnen Still digging in on this; are you able to share the snippet of code where you first define this expectation?

**Comment by austiezr** [comment] 2021-11-23 06:53
@kuhnen We've identified and rectified some unexpected / unwanted behavior around quantile_ranges for this expectation in cases where quantile_ranges were specified not in a min/max order; see #3724. Can you specify your environment for me, and verify that your quantile_ranges adhere to a min/max order?

**Comment by kuhnen** [comment] 2021-11-23 18:42
@austiezr this is the json , does it help?
```json
{"kwargs": {
        "allow_relative_error": false,
        "column": "first_total",
        "quantile_ranges": {
          "quantiles": [
            0.05,
            0.25,
            0.5,
            0.75,
            0.95
          ],
          "value_ranges": [
            [
              -71.53999999999999,
              -72.42
            ],
            [
              12.464374020000001,
              15.013123980000001
            ],
            [
              38.740621080000004,
              42.36187092
            ],
            [
              92.91624019999999,
              98.7487398
            ],
            [
              366.5199706,
              383.51996940000004
            ]
          ]
        }
      }
}
```

**Comment by kuhnen** [comment] 2021-11-23 18:47
and here the validation:
```json
"expectation_config": {
        "expectation_type": "expect_column_quantile_values_to_be_between",
        "ge_cloud_id": null,
        "kwargs": {
          "allow_relative_error": false,
          "column": "total",
          "quantile_ranges": {
            "quantiles": [
              0.05,
              0.25,
              0.5,
              0.75,
              0.95
            ],
            "value_ranges": [
              [
                -71.53999999999999,
                -72.42
              ],
              [
                12.464374020000001,
                15.013123980000001
              ],
              [
                38.740621080000004,
                42.36187092
              ],
              [
                92.91624019999999,
                98.7487398
              ],
              [
                365.5399706,
                382.4999694
              ]
            ]
          },
          "result_format": {
            "result_format": "SUMMARY"
          }
        },
        "meta": {
          "BasicSuiteBuilderProfiler": {
            "confidence": "very low"
          }
        }
      },
      "meta": {
        
      },
      "result": {
        "details": {
          "success_details": [
            false,
            true,
            true,
            true,
            true
          ]
        },
        "element_count": 7076495,
        "missing_count": null,
        "missing_percent": null,
        "observed_value": {
          "quantiles": [
            0.05,
            0.25,
            0.5,
            0.75,
            0.95
          ],
          "values": [
            -72.25,
            13.812499,
            40.749996,
            95.99999,
            373.99997
          ]
        }
      },
      "success": false
    }
```

**Comment by austiezr** [comment] 2021-11-23 19:20
Hey @kuhnen! 

Thanks for getting back with this; I see what's going on here now. Your first value range `[-71.53999999999999, -72.42]` is reversed in order -- Max / Min instead of Min / Max, which leads to them showing out of order in the data docs as well as evaluating `false` in cases where they should succeed. We previously weren't enforcing ordered behavior here, but have now implemented a check to prevent cases like this going forward (see #3724). If you swap that value range to `[-72.42, -71.53999999999999]` you should see this issue resolve!

I'm going to close this issue for now, but feel free to reopen if you don't feel this resolves your case.

**Comment by kuhnen** [comment] 2021-11-24 08:22
@austiezr thanks for the answer.  The only problem that I have is that we are creating these expectations using the profiler. 
Do you have anything in mind about how to fix this?  Thanks a lot for the quick reply.

**Comment by austiezr** [comment] 2021-11-24 17:53
Hey @kuhnen! Which profiler are you using?

**Comment by kuhnen** [comment] 2021-11-25 06:48
hey @austiezr  we are using 
```
ge.profile.BasicSuiteBuilderProfiler().profile(
            data_asset=batch,
            profiler_configuration=self.create_auto_profiling_config(batch),
        )
```
and I just did run the latest version 0.13.44 and I still have the exact same issue.   Any idea how I could help?  But I believe the issue is on the profiler and the validation is not being checked if it is in order.  
Thanks a lot for your work 👍

**Comment by austiezr** [comment] 2021-11-30 21:54
Hey @kuhnen! Thanks for this, we'll keep trying to hunt this down. Would you be able to share the profiler config you're using above?

**Comment by kuhnen** [comment] 2021-12-02 07:42
Hello @austiezr I need to log the config, I can do that, but looking at the code it looks very basic.   Maybe this helps? ```
![image](https://user-images.githubusercontent.com/1311776/144378807-c8e4d96e-f054-4ae2-b7af-fccd13855ad6.png)
```

**Comment by austiezr** [comment] 2021-12-15 21:17
Hey @kuhnen! I've been unable to replicate this behavior on V2 or V3 of Great Expectations with BasicSuiteBuilderProfiler; are you able to share that profiling config, and verify which version & release of GE you're experiencing this behavior with?

**Comment by austiezr** [comment] 2022-01-12 16:37
Hey @kuhnen! I'm going to close this out for now; if you're still encountering this issue and can provide further context, feel free to re-open and reach out! We would encourage looking into the User-Configurable and Rule-Based profilers. They're more powerful than the older profilers, and safer, as the older profilers can sometimes have unintended behaviors.

**Closed as completed by austiezr** 2022-01-12 16:37 UTC
Labels: community, devrel, bounty-board
