### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by Aylr** [fivetran/great_expectations#1945] opened 2020-10-01 22:49 UTC
**Describe the bug**
When running a `checkpoint` the slack message renderer explodes unpleasantly.
**To Reproduce**
1. Set up a GCS site like:
```yaml
 gcs_site:
    class_name: SiteBuilder
    store_backend:
      class_name: TupleGCSStoreBackend
      bucket: my-bucket
      prefix: ''
      project: my-project
      base_public_path: https://datadocs.my-domain.com  # External url
    site_index_builder:
      class_name: DefaultSiteIndexBuilder
      show_cta_footer: true
    show_how_to_buttons: true
```
2. Run a checkpoint
3. See error

```
❯ great_expectations checkpoint run tiny-test
Heads up! This feature is Experimental. It may change. Please give us your feedback!
Error running action with name send_slack_notification_on_validation_result
Traceback (most recent call last):
  File "/Users/taylor/repos/project/venv/lib/python3.8/site-packages/great_expectations/validation_operators/validation_operators.py", line 380, in _run_actions
    action_result = self.actions[action["name"]].run(
  File "/Users/taylor/repos/project/venv/lib/python3.8/site-packages/great_expectations/validation_operators/actions.py", line 46, in run
    return self._run(
  File "/Users/taylor/repos/project/venv/lib/python3.8/site-packages/great_expectations/validation_operators/actions.py", line 164, in _run
    query = self.renderer.render(
  File "/Users/taylor/repos/project/venv/lib/python3.8/site-packages/great_expectations/render/renderer/slack_renderer.py", line 69, in render
    report_element = self._get_report_element(docs_link)
  File "/Users/taylor/repos/project/venv/lib/python3.8/site-packages/great_expectations/render/renderer/slack_renderer.py", line 142, in _get_report_element
    if "file:///" in docs_link:
TypeError: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/Users/taylor/repos/project/venv/bin/great_expectations", line 8, in <module>
    sys.exit(main())
  File "/Users/taylor/repos/project/venv/lib/python3.8/site-packages/great_expectations/cli/cli.py", line 72, in main
    cli()
  File "/Users/taylor/repos/project/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/taylor/repos/project/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/taylor/repos/project/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/taylor/repos/project/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/taylor/repos/project/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/taylor/repos/project/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/taylor/repos/project/venv/lib/python3.8/site-packages/great_expectations/cli/mark.py", line 28, in wrapper
    func(*args, **kwargs)
  File "/Users/taylor/repos/project/venv/lib/python3.8/site-packages/great_expectations/cli/checkpoint.py", line 297, in checkpoint_run
    results = context.run_validation_operator(
  File "/Users/taylor/repos/project/venv/lib/python3.8/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 257, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "/Users/taylor/repos/project/venv/lib/python3.8/site-packages/great_expectations/data_context/data_context.py", line 1003, in run_validation_operator
    return validation_operator.run(
  File "/Users/taylor/repos/project/venv/lib/python3.8/site-packages/great_expectations/validation_operators/validation_operators.py", line 329, in run
    batch_actions_results = self._run_actions(
  File "/Users/taylor/repos/project/venv/lib/python3.8/site-packages/great_expectations/validation_operators/validation_operators.py", line 399, in _run_actions
    raise e
  File "/Users/taylor/repos/project/venv/lib/python3.8/site-packages/great_expectations/validation_operators/validation_operators.py", line 380, in _run_actions
    action_result = self.actions[action["name"]].run(
  File "/Users/taylor/repos/project/venv/lib/python3.8/site-packages/great_expectations/validation_operators/actions.py", line 46, in run
    return self._run(
  File "/Users/taylor/repos/project/venv/lib/python3.8/site-packages/great_expectations/validation_operators/actions.py", line 164, in _run
    query = self.renderer.render(
  File "/Users/taylor/repos/project/venv/lib/python3.8/site-packages/great_expectations/render/renderer/slack_renderer.py", line 69, in render
    report_element = self._get_report_element(docs_link)
  File "/Users/taylor/repos/project/venv/lib/python3.8/site-packages/great_expectations/render/renderer/slack_renderer.py", line 142, in _get_report_element
    if "file:///" in docs_link:
TypeError: argument of type 'NoneType' is not iterable
```

**Expected behavior**
I expect a slack message to be sent.

**Environment (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - GE Version: [e.g. 0.10.0] 0.12.3

**Additional Context**

I ran `great_expectations docs build` then the same checkpoint again and it behaved as expected so there is some unknown state issue here.

**Comment by eugmandel** [comment] 2020-12-01 00:11
Duplicate of #2062

**Closed as completed** 2020-12-01 00:10 UTC
Labels: bug
