### ISSUE TITLE
Extend documentation for removing expectations

### ISSUE THREAD

**Issue by HansBambel** [fivetran/great_expectations#3616] opened 2021-10-29 12:42 UTC
**Is your feature request related to a problem? Please describe.**
I am new to great_expectations and went through the "Getting started" set up with my own data. After setting up the expectation suite I went over it again because I noticed some of the expectations were not as I wanted them to be or were not useful at all.

I started the editing process with `great_expectations --v3-api suite edit <my-suite>` and since I was told that all expectations from the suite are in the notebook that was opened I expected that when I delete those cells of the expectations that I do not want anymore that they would be removed from the suite as well. I learned that this is not the case and I need to remove them manually. But even after reading the [docs](https://docs.greatexpectations.io/docs/reference/expectation_suite_operations) and trying out the function

```
suite.remove_Expectation(
    expectation_configuration, 
    match_type, 
    remove_multiple_matches
)
```

I did not manage to remove them.

The docs say that I need "an `ExpectationConfiguration` object that is used to determine whether and where this Expectation already exists within the Suite", but it is nowhere shown where this object is supposedly coming from. The notebook creates expectations using `validator.expect_column_values_to_be_in_set(column="is_clean", value_set=[False, True])`, but there is no object that can be used for the `remove_Expectation` function.

I also tried the following:
`suite.remove_expectation(ge.core.expectation_configuration.ExpectationConfiguration("expect_column_values_to_be_null", kwargs={"column": "<my_column>"}))` which seemed to remove the expectation (as this cell was only possible to be executed once, because the second time no matching expectation was found), but the suite still had the expectation.

Using `validator.remove_expectation` gave me a deprecation warning, so I stuck with `suite.remove_expectation`.
**EDIT: fixed first call**

**Describe the solution you'd like**
A clear and concise description of how to remove expectations with examples.

**Describe alternatives you've considered**
An alternative that I did was delete the .json that contains my expectations suite and create it anew with `great_expectations --v3-api suite new <my-suite>` and delete the undesired expectations there already, but I doubt that this is the desired way of removing unwanted expectations as all custom written ones would be lost as well.

Another alternative would be to manually delete the expectations in the .json, but I also doubt that this is desired.

**Comment by talagluck** [comment] 2021-11-01 13:43
Hi @HansBambel - thank you very much for opening this issue! This is great feedback, and we will work on updating our docs to make this more understandable.

One quick question regarding:
> Using suite.remove_expectation gave me a deprecation warning, so I stuck with suite.remove_expectation

Would you please clarify this?

Off the top of my head, the right way to do this is just as you did, except instead of `suite.remove_expectation`, you would use `validator.get_expectation_suite().remove_expectation`. I recognize that this is not intuitive, and will require updated documentation, so thank you again!

**Comment by HansBambel** [comment] 2021-11-01 18:20
Oh, yes. My mistake. I used `validator.remove_expectation` and that got me the warning.

**Comment by HansBambel** [comment] 2021-11-05 13:11
@talagluck I tried using 
```
validator.get_expectation_suite().remove_expectation(ge.core.expectation_configuration.ExpectationConfiguration("expect_column_values_to_be_null", kwargs={"column": "<my_column>"})
```
but the expectation was not removed. 

I think the best workflow for removing an expectation from an existing suite is:
1. use `great_expectations --v3-api suite edit <my-suite>`
2. Delete the `expectation/<my-suite>.json`
3. Delete/edit the cells in the notebook which you want to remove/edit
4. Run the notebook (it creates a new `<my-suite>.json`)

**Comment by talagluck** [comment] 2021-11-24 14:24
Hi @HansBambel - thanks again for raising this! We are currently in the process of re-tooling both the functionality and the documentation for this feature. I have confirmed that at this stage, `validator.remove_expectation` is the way to go, despite the DeprecationWarning.

**Comment by HansBambel** [comment] 2021-11-24 18:06
Great, thanks for the update!

**Comment by frantakalab** [comment] 2021-12-22 09:04
+1. For me the most straight forward solution would be to delete the cells with expectations I don't want and execute the cells with expectations I do want. I was able to get the desired behavior by changing the following part of code in the edit notebook's 1st cell:
```python
try:
    suite = context.get_expectation_suite(expectation_suite_name=expectation_suite_name)
    print(
        f'Loaded ExpectationSuite "{suite.expectation_suite_name}" containing {len(suite.expectations)} expectations.'
    )
except DataContextError:
    suite = context.create_expectation_suite(
        expectation_suite_name=expectation_suite_name
    )
    print(f'Created ExpectationSuite "{suite.expectation_suite_name}".')
```
to:
```python
suite = context.create_expectation_suite(expectation_suite_name=expectation_suite_name, overwrite_existing=True)
print(f'Created ExpectationSuite "{suite.expectation_suite_name}".')
```

**Comment by HansBambel** [comment] 2021-12-22 12:19
I agree, that would be even better. Since the expectations are parsed from the current state anyway and I am expected to run the whole notebook. This basically is creating a new expectation-suite anyway.

**Comment by marksimpson82** [comment] 2022-07-14 21:46
Can +1 this. I had the same experience as @HansBambel. 

I've subsequently shown several people how to use GE profilers & interactive editing of expectation suites, and I've yet to see anyone organically figure out how to use `remove_expectation` (though in fairness, most of the users don't know python very well -- they're still learning). 

From ad-hoc screensharing and helping with GE, the usual pattern I see is users delete expectation cells from the notebook and think it will remove these expectations from the suite. They're surprised when it doesn't work like that.

I usually just delete the expectations from the expectation suite .json and re-launch the notebook. That works for people just fine, but it's a bit clunky and un-intuitive.

**Comment by talagluck** [comment] 2023-03-08 13:11
Closing since we've updated our docs on `remove_expectation` here: https://docs.greatexpectations.io/docs/reference/api/core/expectationsuite_class/

Thanks again for all your feedback!

**Closed as completed by talagluck** 2023-03-08 13:11 UTC
Labels: devrel
