### ISSUE TITLE
Error running GreatExpectationsOperator

### ISSUE THREAD

**Issue by henriqueribeiro** [fivetran/great_expectations#3114] opened 2021-07-26 13:47 UTC
**Describe the bug**
When running a great_expectation suite on Google Cloud Composer using BigQuery as a datasource, I'm getting the follwing error:
```
[2021-07-23 17:40:24,866] {xcom.py:237} ERROR - Could not serialize the XCom value into JSON. If you are using pickles instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config.
[2021-07-23 17:40:24,866] {taskinstance.py:1457} ERROR - Object of type ValidationOperatorResult is not JSON serializable
Traceback (most recent call last):
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1113, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1287, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1320, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/utils/session.py", line 65, in wrapper
    return func(*args, session=session, **kwargs)
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1896, in xcom_push
    XCom.set(
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/utils/session.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/models/xcom.py", line 88, in set
    value = XCom.serialize_value(value)
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/models/xcom.py", line 235, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/opt/python3.8/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/opt/python3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/python3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/python3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ValidationOperatorResult is not JSON serializable
``` 

**To Reproduce**

1. [Dag File](https://github.com/great-expectations/great_expectations/files/6878622/dag.py.txt)
2. [GE config file](https://github.com/great-expectations/great_expectations/files/6878633/great_expectations.yml.txt)
3. [GE suite](https://github.com/great-expectations/great_expectations/files/6878639/suite_tableY.json.txt)

**Expected behavior**
It should run and push the result to XComs

**Environment (please complete the following information):**
 - Cloud Composer Verison: 1.17.0
 - Airflow Version: 2.0.2
 - Great Expectations Version: 0.13.22

**Additional context**
If I set `do_xcom_push` to `False` it works but I can't fetch the results after execution.

**Comment by talagluck** [comment] 2021-08-03 20:23
Hi @henriqueribeiro - thanks for submitting this issue! It appears this is a duplicate of https://github.com/great-expectations/airflow-provider-great-expectations/issues/35, so I will be closing this for right now. I'll be in touch in the other Issue in the next day or so.

**Closed as completed by talagluck** 2021-08-03 20:23 UTC
Labels: community, devrel
