### ISSUE TITLE
'NoneType' object has no attribute 'setCallSite'

### ISSUE THREAD

**Issue by hugh-nguyen** [fivetran/great_expectations#4812] opened 2022-04-07 04:19 UTC
**Describe the bug**
I am getting the following error when running a checkpoint on a spark dataframe.
```
Traceback (most recent call last):
File "/home/spark/.local/lib/python3.7/site-packages/great_expectations/validator/validator.py", line 1166, in resolve_validation_graph
runtime_configuration=runtime_configuration,
File "/home/spark/.local/lib/python3.7/site-packages/great_expectations/validator/validator.py", line 2073, in _resolve_metrics
runtime_configuration=runtime_configuration,
File "/home/spark/.local/lib/python3.7/site-packages/great_expectations/execution_engine/execution_engine.py", line 402, in resolve_metrics
message=str(e), failed_metrics=[x[0] for x in metric_fn_bundle]
great_expectations.exceptions.exceptions.MetricResolutionError: 'NoneType' object has no attribute 'setCallSite'
```

**To Reproduce**
I have this code that reads in data from memory into a Pandas DF and it works fine.
```python
import sys
from pyspark.context import SparkContext
from great_expectations.data_context.types.base import DataContextConfig, DatasourceConfig, S3StoreBackendDefaults
from great_expectations.data_context import BaseDataContext
from great_expectations.profile import BasicSuiteBuilderProfiler
from great_expectations.data_context.types.resource_identifiers import ValidationResultIdentifier
from great_expectations.core import ExpectationConfiguration
from great_expectations.core.batch import RuntimeBatchRequest

sc = SparkContext()

data_context_config = DataContextConfig(
    config_version=2,
    plugins_directory=None,
    config_variables_file_path=None,
    datasources={
        
    },
    stores={
        "expectations_S3_store": {
            "class_name": "ExpectationsStore",
            "store_backend": {
                "class_name": "TupleS3StoreBackend",
                "bucket": "metigy-dq-dev-test", #Bucket storing great_expectations suites results
                "prefix": "expectations/", #Trailing slash is important
            },
        },
        "validations_S3_store": {
            "class_name": "ValidationsStore",
            "store_backend": {
                "class_name": "TupleS3StoreBackend",
                "bucket": "metigy-dq-dev-test",
                "prefix": "validations/"
            },
        },
        "evaluation_parameter_store": {"class_name": "EvaluationParameterStore"},
        "checkpoint_store": {
            "class_name": "CheckpointStore",
            "store_backend": {
                "class_name": "TupleS3StoreBackend",
                "bucket": "metigy-dq-dev-test",
                "prefix": "checkpoints/"
            },
        },
    },
    expectations_store_name="expectations_S3_store",
    validations_store_name="validations_S3_store",
    evaluation_parameter_store_name="evaluation_parameter_store",
    checkpoint_store_name="checkpoint_store",
    data_docs_sites={
        "s3_site": {
            "class_name": "SiteBuilder",
            "store_backend": {
                "class_name": "TupleS3StoreBackend",
                "bucket":  "metigy-dq-dev-test",
                "prefix":  "data_docs/",
            },
            "site_index_builder": {
                "class_name": "DefaultSiteIndexBuilder",
                "show_cta_footer": True,
            },
        }
    },
    validation_operators={
        "action_list_operator": {
            "class_name": "ActionListValidationOperator",
            "action_list": [
                {
                    "name": "store_validation_result",
                    "action": {"class_name": "StoreValidationResultAction"},
                },
                {
                    "name": "store_evaluation_params",
                    "action": {"class_name": "StoreEvaluationParametersAction"},
                },
                {
                    "name": "update_data_docs",
                    "action": {"class_name": "UpdateDataDocsAction"},
                },
            ],
        }
    },
    anonymous_usage_statistics={
      "enabled": True
    }
)


data = [
    {"product": 'APPLE', "ID": 1, "Value": 121.44, "Truth": True},
    {"product": 'BANANNA', "ID": 2, "Value": 300.01, "Truth": False},
    {"product": 'APPLE', "ID": 3, "Value": 10.99, "Truth": True},
    {"product": 'APPLE', "ID": 4, "Value": 33.87, "Truth": True}
]

# rdd = sc.parallelize(data)
# df_1 = rdd.toDF()
# print(df_1.show())
import pandas as pd
df_1 = pd.DataFrame(data=data)

context = BaseDataContext(project_config=data_context_config)
datasource_config = {
    "name": "taxi_datasource",
    "class_name": "Datasource",
    "execution_engine": {
        # "class_name": "SparkDFExecutionEngine",
        "class_name": "PandasExecutionEngine",
    },
    "data_connectors": {
        "default_runtime_data_connector_name": {
            "class_name": "RuntimeDataConnector",
            "batch_identifiers": ["batch_id"],
        },
    },
}
context.add_datasource(**datasource_config)

suite = context.create_expectation_suite("my_expectation_suite", overwrite_existing=True)

expectation_configuration = ExpectationConfiguration(
   expectation_type="expect_column_values_to_be_in_set",
   kwargs={
      "column": "product",
      "value_set": ['APPLE', 'BANANNA', 'CARROT', 'ORANGE', 'MELON', 'LEMON']
   },
)
suite.add_expectation(expectation_configuration=expectation_configuration)
context.save_expectation_suite(suite, "my_expectation_suite")

# Python <snippet>
checkpoint_config = {
    "name": "my_missing_batch_request_checkpoint",
    "config_version": 1,
    "class_name": "SimpleCheckpoint",
    "expectation_suite_name": "my_expectation_suite",
}
context.add_checkpoint(**checkpoint_config)

batch_request_1 = RuntimeBatchRequest(
    datasource_name="taxi_datasource",
    data_connector_name="default_runtime_data_connector_name",
    data_asset_name="taxi_data",
    runtime_parameters={"batch_data": df_1},
    batch_identifiers={"batch_id": "default_identifier"},
)

results = context.run_checkpoint(
    checkpoint_name="my_missing_batch_request_checkpoint",
    run_name="test_run",
    validations=[
        {"batch_request": batch_request_1},
    ],
)

context.build_data_docs()
```

Now when I change the class_name of the datasource from "PandasExecutionEngine" to "SparkDFExecutionEngine", and change
```python
import pandas as pd
df_1 = pd.DataFrame(data=data)
```
to
```
rdd = sc.parallelize(data)
df_1 = rdd.toDF()
print(df_1.show())
```

I can confirm that the dataframe works, but I get an the error below when I few the results
'NoneType' object has no attribute 'setCallSite' 
![image](https://user-images.githubusercontent.com/30641101/162119188-2fa9f1e9-493c-44a8-bfc0-f7cf2806d0c6.png)

**Expected behavior**
All expectations should pass

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.14.13

**Additional context**
I've tried several different versions and get the same results

**Comment by talagluck** [comment] 2022-04-11 16:03
Thanks for opening this, @hugh-nguyen! We will review and be in touch.

**Comment by vatj** [comment] 2022-04-21 12:10
Any news on this? Could this be related to the spark version? I am getting the same error when running a colab notebooks with pyspark:
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/great_expectations/execution_engine/execution_engine.py", line 398, in resolve_metrics
    new_resolved = self.resolve_metric_bundle(metric_fn_bundle)
  File "/usr/local/lib/python3.7/dist-packages/great_expectations/execution_engine/sparkdf_execution_engine.py", line 645, in resolve_metric_bundle
    res = df.agg(*aggregate_cols).collect()
  File "/content/spark-3.2.1-bin-hadoop3.2/python/pyspark/sql/dataframe.py", line 692, in collect
    with SCCallSiteSync(self._sc) as css:
  File "/content/spark-3.2.1-bin-hadoop3.2/python/pyspark/traceback_utils.py", line 72, in __enter__
    self._context._jsc.setCallSite(self._call_site)
AttributeError: 'NoneType' object has no attribute 'setCallSite'
```

**Comment by Halpph** [comment] 2022-04-28 09:22
I saw another response in a similar issue, apparently the solution is to add force_reuse_spark_context =True to the execution engine.
i.e.:
`datasource_config = {
    "name": table,
    "class_name": "Datasource",
    "execution_engine": {"class_name": "SparkDFExecutionEngine",
    "force_reuse_spark_context": "true"},
    "data_connectors": {
        "default_runtime_data_connector_name": {
            "class_name": "RuntimeDataConnector",
            "batch_identifiers": ["batch_id"],
        }
      },
      }
    context.add_datasource(**datasource_config)`

**Comment by vatj** [comment] 2022-04-28 10:06
Thanks for sharing your solutions, will give it a shot again

**Comment by mkopec87** [comment] 2022-06-03 14:59
I observed similar symptoms. The problem was that you create your Spark dataframe using SparkContext created in the beginning of the file. Later, when you create Data Context, the Spark session is created again, and it doesn't have the reference to your dataframe.

I solved it via creating the SparkContext via:
```
sc = ge.core.util.get_or_create_spark_application()
```
instead of:
```
sc = SparkContext()
```

**Comment by Halpph** [comment] 2022-06-03 15:05
@mkopec87 yes, I totally agree, initially I was doing like I wrote, but then I realized that if you run for example tests in parallel, they would easily fail because they are always reusing the same spark context.
Eventually I switched to your solution, that I believe is the preferred one!
Thanks for updating this issue.

**Comment by talagluck** [comment] 2022-08-10 08:29
Hi @hugh-nguyen, @vatj, @Halpph, @mkopec87 - thank you for your patience here. To better understand this, do you believe this to be a bug in Great Expectations functionality that you have solved with a workaround which requires a bugfix? Or do you think this is more of a set-up issue, which requires us to improve our documentation?

**Comment by kirilscherbach** [comment] 2022-11-07 18:37
I've encountered this issue with GX 0.15.31 (RuntimeDataConnector + SparkDFExecutionEngine) on AWS Glue v3. It was a bit of a surprise - on PySpark 2.4.8 I was able to initiate spark session 
```
spark = SparkSession.builder.appName("Name").enableHiveSupport().getOrCreate()
```
and then run GX checkpoint.

In Glue I tried adding `force_reuse_spark_context: true` - it did not help. In the end I was able to run the checkpoint successfully by using the method by @mkopec87 :
```
sc = gx.core.util.get_or_create_spark_application()
glueContext = GlueContext(sc)
spark = glueContext.spark_session
```

**Comment by wagneralbjr** [comment] 2022-12-16 12:06
I'm also facing this bug.
What about the default be changed to reuse the spark session and the context that is already created?
@mkopec87  solution works.

Another workaround that i have found is to set the app name to `default_great_expectations_spark_application`

Like this
`spark = SparkSession.builder.appName("default_great_expectations_spark_application").getOrCreate()
`

If you set to this name, it works, but i don't know why.

**Comment by billdirks** [comment] 2023-05-10 23:40
Hi @hugh-nguyen, thanks for reporting this issue. I believe @mkopec87 has provided a workaround (thank you!). I also can not reproduce this using your code snippet and the latest version of Great Expectations. That is, if I run your code with your substitutions:
* Change `PandasExecutionEngine` to `SparkDFExecutionEngine`
* Change
```
import pandas as pd
df_1 = pd.DataFrame(data=data)
```
to
```
rdd = sc.parallelize(data)
df_1 = rdd.toDF()
print(df_1.show())
```

* And the additional substitution:
```
sc = SparkContext()
```
to
```
import pyspark

sc = SparkContext()
spark_session = pyspark.sql.SparkSession(sc)
```
everything works for me. Without creating `spark_session` I hit the pyspark error: ` raise RuntimeError("""RDD.toDF was called before SparkSession was initialized.""")` on the line `df_1 = rdd.toDF()`. That could be due to me using a different spark version than you used.

These are the versions I have installed:
Great Expectations: 0.16.11
Pyspark: 3.3.2
Python 3.10.3
boto3: 1.26.132

Please let me know if you still have an issue or I will close this ticket shortly.

**Comment by billdirks** [comment] 2023-05-12 23:40
I'm going to close this as it looks resolved. Please reopen this if you see this again on the latest version of Great Expectations.

**Closed as completed by billdirks** 2023-05-12 23:41 UTC
Labels: community, devrel
