### ISSUE TITLE
Cannot create data context in Azure Databricks cluster with ADLS Passthrough enabled

### ISSUE THREAD

**Issue by amybachir** [fivetran/great_expectations#3690] opened 2021-11-17 04:47 UTC
I'm using great_expectations version 0.13.33. I'm running great_expectation in an Azure Databricks cluster with [ADLS Credential Passthrough](https://docs.microsoft.com/en-us/azure/databricks/security/credential-passthrough/adls-passthrough) enabled. All my stores are `TupleFilesystemStoreBackend` that are Databricks DBFS mounts with Azure blob storage backend.

I'm unable to create a data context when I use an Azure Databricks cluster with ADLS Credential Passthrough. It fails with the following error:
```
Invalid store configuration: Please check the configuration of your TupleFilesystemStoreBackend named expectations_store
```
However, the same exact code is able to succesfully create a data context on standarad Azure Databricks cluster that is configured with a service principal. I haven't been able to pinpoint the issue yet.

Here is my data context:
```
    expectation_store_dir="/mnt/greatexpectations/expectations"
    validation_store_dir="/mnt/greatexpectations/validations"
    docs_store_dir="/mnt/greatexpectations/docs"

    project_config = DataContextConfig(
        config_version=2,
        plugins_directory=None,
        config_variables_file_path=None,

        datasources={
            "spark_datasource": {
                "data_asset_type": {
                    "class_name": "CustomSparkDFValidations",
                    "module_name": "SDPaaS_data_validation.validate",
                },
                "class_name": "SparkDFDatasource",
                "module_name": "great_expectations.datasource",
                "batch_kwargs_generators": {},
            }
        },
        stores={
        "expectations_store": {
            "class_name": "ExpectationsStore",
            "store_backend": {
                "class_name": "TupleFilesystemStoreBackend",
                "base_directory": "/dbfs" + expectation_store_dir,
            },
        },
        "validations_store": {
            "class_name": "ValidationsStore",
            "store_backend": {
                "class_name": "TupleFilesystemStoreBackend",
                "base_directory": "/dbfs" + validation_store_dir,
            },
        },
        "evaluation_parameter_store": {"class_name": "EvaluationParameterStore"},
    },
    expectations_store_name="expectations_store",
    validations_store_name="validations_store",
    evaluation_parameter_store_name="evaluation_parameter_store",
    data_docs_sites={
        "local_site": {
            "class_name": "SiteBuilder",
            "store_backend": {
                "class_name": "TupleFilesystemStoreBackend",
                "base_directory": "/dbfs" + docs_store_dir,
            },
            "site_index_builder": {
                "class_name": "DefaultSiteIndexBuilder",
                "show_cta_footer": True,
            },
        }
    },
    validation_operators={
    "action_list_operator": {
        "class_name": "ActionListValidationOperator",
        "action_list": [
            {
                "name": "store_validation_result",
                "action": {"class_name": "StoreValidationResultAction"},
            },
            {
                "name": "store_evaluation_params",
                "action": {"class_name": "StoreEvaluationParametersAction"},
            },
            {
                "name": "update_data_docs",
                "action": {"class_name": "UpdateDataDocsAction"},
            },
        ],
    }
    },
    anonymous_usage_statistics={
    "enabled": True
    }
    )

    context = BaseDataContext(project_config=project_config)
```

**Comment by talagluck** [comment] 2021-11-17 16:44
Thanks for opening this issue, @amybachir! We will review and be in touch soon. I wanted to confirm, do you think that this may be a duplicate of #3538?

**Comment by amybachir** [comment] 2021-11-17 16:51
@talagluck thanks for looking into this. I believe this is a different issue than `3538`. This issue is related to connecting to the backend store when creating a data context. In `3538`, it seems they were able to create a data context but came across an error when attempting to create a Spark session which I ran into when I got past creating the data context.

I was able to get past the data context issue by specifying a new dbfs mount point. When I attempted to use a mount point that was previously created and mounted by a different user (service principal in this case), great_expectations threw an invalid configurations error but when I changed the mount point name, it succeeded.

The above didn't make a lot of sense to me because I'm un-mounting and remounting the mount point with every session but at least I got around the error.

**Comment by talagluck** [comment] 2021-11-22 16:07
Hi @amybachir - thank you for the follow-up and description of your work-around, the context is really helpful. After some internal conversation, it sounds like ADLS Passthrough is probably not something we'll be able to prioritize immediately. That said, we are adding it to our backlog, and of course, we always welcome community contributions in case you, or anyone else, are interested!

**Comment by DaveRuijter** [comment] 2022-01-17 13:59
I can confirm this behaviour. The 'monkey patch' is working nicely.
It would be great of course if this is integrated in the library.
Thanks in advance!

**Closed as completed** 2023-03-07 16:41 UTC
Labels: help wanted, community, feature
