### ISSUE TITLE
Spark Context has stopped on Dataricks

### ISSUE THREAD

**Issue by sawyee** [fivetran/great_expectations#2561] opened 2021-03-17 18:28 UTC
Hi there, 

**Bug Description**
I am attempting to follow the example as shown in the documentation [here](
https://docs.greatexpectations.io/en/latest/guides/how_to_guides/configuring_data_contexts/how_to_instantiate_a_data_context_on_a_databricks_spark_cluster.html) for using great expectations on Databricks. 

However  whenever I try to instantiate the great expectations context, the spark context seems to stop, displaying the following error message:

```
The spark context has stopped and the driver is restarting. Your notebook will be automatically reattached.
```

One of my colleagues also had an example of great expectations that was working on Databricks, until today, when he also got the `spark context has stopped` error.

**To Reproduce**
Attempt to run the first snippet of [this](
https://docs.greatexpectations.io/en/latest/guides/how_to_guides/configuring_data_contexts/how_to_instantiate_a_data_context_on_a_databricks_spark_cluster.html) in a Databricks notebook cell.

**Expected behavior**
The client is instantiated correctly

**Environment (please complete the following information):**
Databricks run time 7.3 LTS

**Comment by eugmandel** [comment] 2021-03-17 22:58
@sawyee Are you setting spark.app.name? If yes, and you are running a recent release of Great Expectation, you should see this behavior. The solution is not to set the custom app name when running interactively in a Databricks notebook. Could you please confirm? Thank you!

**Comment by sawyee** [comment] 2021-03-18 08:43
Hi @eugmandel I haven't manually set the spark.app.name configuration, but the result of 
`spark.conf.get("spark.app.name")` is `Databricks Shell`

Thanks

**Comment by jarandaf** [comment] 2021-03-19 10:51
Hi @eugmandel, I am also experiencing the same issue with the same Databricks runtime. Is there any work around?

EDIT:

After having a look at the code, I think [this](https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/core/util.py#L482) may be root cause. I don't understand why the spark context needs to be stopped but this just breaks Databricks runtimes.

**Comment by jarandaf** [comment] 2021-03-19 14:04
Downgrading to version 0.13.12 seems to work. 90ed2ba8dc003b1c11581a64e280455d4bd08dad seems to introduce the breaking changes.

**Comment by eugmandel** [comment] 2021-03-19 15:05
@sawyee Thank you for replying re custom app name!, @jarandaf Thank you for pointing to that commit! 

Yes, then this does look like a bug - the core team will take it on.

**Comment by eugmandel** [comment] 2021-03-19 15:08
@alexsherstinsky Could you please take a look at this? Thank you!

**Comment by alexsherstinsky** [comment] 2021-03-19 16:26
I am looking at it now.  Thank you to the users for reporting it.

**Comment by alexsherstinsky** [comment] 2021-03-20 01:30
Thank you, @jarandaf -- it appears that our implementation of wanting to honor the developer's desire to specify his/her own custom `spark.app.name` is not working with `Databricks`, where the system value of this property is `Databricks Shell`.  Apparently, once stopped, `SparkContext` is having difficulties being restarted.  I was able to reproduce the issue -- thanks!

Moreover, we conducted further troubleshooting and discovered that accessing `SparkContext` from a local `Jupyter` notebook (in `Jupyter Lab`) also differs in behavior from that as part of standard `Python` on a local machine (e.g., in `pytest`).  Specifically, certain references (such as `sparkSession.SparkContext`) are `NULL` in a notebook cell, while a proper object reference in the standard `Python`.  However, further dereferencing produces the expected results.

We modified the code to sacrifice a little bit of readability in favor of a more consistent behavior between standard `Python` and `Jupyter` notebooks, and issued PR #2574 .  Next week, we will test on `Databricks` and report our findings herein.

Thank you very much for finding and reporting this issue.  We will communicate again next week.  Have a great weekend!

**Comment by alexsherstinsky** [comment] 2021-03-22 19:24
Hello again @jarandaf -- the above mentioned PR has been merged into the `develop` branch.  If you are able to load `great_expectations` from that branch, could you please re-test your notebook in Databricks and let us know whether or not the issue is still present?  Otherwise, we can test it in a couple of days when the next release is published.  Thank you!

**Comment by jarandaf** [comment] 2021-03-23 08:53
Hi @alexsherstinsky, thank you for the PR. I was able to try the latest develop changes (414e45ba9980fa033abf119e9c38421a807561c1) and It seems the spark context keeps getting stopped though.

**Closed as completed** 2021-03-25 15:55 UTC
Labels: bug
