### ISSUE TITLE
NameError: name 'WithinGroup' is not defined

### ISSUE THREAD

**Issue by shahinism** [fivetran/great_expectations#1450] opened 2020-05-16 10:00 UTC
**Describe the bug**
After installing the new released version from Pypi (version 0.10.11), invoking great expectation will raise following exception:

```
$ great_expectations --version
Traceback (most recent call last):
  File "/home/hadoop/.local/bin/great_expectations", line 7, in <module>
    from great_expectations.cli import main
  File "/home/hadoop/.local/lib/python3.6/site-packages/great_expectations/__init__.py", line 7, in <module>
    from great_expectations.data_context import DataContext
  File "/home/hadoop/.local/lib/python3.6/site-packages/great_expectations/data_context/__init__.py", line 3, in <module>
    from .data_context import BaseDataContext, DataContext, ExplorerDataContext
  File "/home/hadoop/.local/lib/python3.6/site-packages/great_expectations/data_context/data_context.py", line 20, in <module>
    from great_expectations.core.usage_statistics.usage_statistics import (
  File "/home/hadoop/.local/lib/python3.6/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 20, in <module>
    from great_expectations.core.usage_statistics.anonymizers.data_docs_site_anonymizer import (
  File "/home/hadoop/.local/lib/python3.6/site-packages/great_expectations/core/usage_statistics/anonymizers/data_docs_site_anonymizer.py", line 2, in <module>
    from great_expectations.core.usage_statistics.anonymizers.site_builder_anonymizer import (
  File "/home/hadoop/.local/lib/python3.6/site-packages/great_expectations/core/usage_statistics/anonymizers/site_builder_anonymizer.py", line 2, in <module>
    from great_expectations.render.renderer.site_builder import (
  File "/home/hadoop/.local/lib/python3.6/site-packages/great_expectations/render/renderer/__init__.py", line 7, in <module>
    from .other_section_renderer import ProfilingResultsOverviewSectionRenderer
  File "/home/hadoop/.local/lib/python3.6/site-packages/great_expectations/render/renderer/other_section_renderer.py", line 4, in <module>
    from great_expectations.profile.basic_dataset_profiler import BasicDatasetProfiler
  File "/home/hadoop/.local/lib/python3.6/site-packages/great_expectations/profile/__init__.py", line 1, in <module>
    from .basic_dataset_profiler import BasicDatasetProfiler
  File "/home/hadoop/.local/lib/python3.6/site-packages/great_expectations/profile/basic_dataset_profiler.py", line 3, in <module>
    from great_expectations.profile.base import (
  File "/home/hadoop/.local/lib/python3.6/site-packages/great_expectations/profile/base.py", line 8, in <module>
    from ..dataset import Dataset
  File "/home/hadoop/.local/lib/python3.6/site-packages/great_expectations/dataset/__init__.py", line 3, in <module>
    from .dataset import Dataset
  File "/home/hadoop/.local/lib/python3.6/site-packages/great_expectations/dataset/dataset.py", line 13, in <module>
    from great_expectations.dataset.util import (
  File "/home/hadoop/.local/lib/python3.6/site-packages/great_expectations/dataset/util.py", line 578, in <module>
    selects: List[WithinGroup], sql_engine_dialect: DefaultDialect
NameError: name 'WithinGroup' is not define
```

**To Reproduce**
Steps to reproduce the behaviour:
1. `pip install great-expectations`
2. `great_expectations --version`

**Expected behaviour**
To not raise the exception. 

**Environment (please complete the following information):**
 - OS: Linux
 - GE Version: 0.10.11

**Comment by eugmandel** [comment] 2020-05-16 15:49
@shahinism Thank you for reporting this! Which database were you connecting to?

**Comment by kokes** [comment] 2020-05-16 16:50
Duplicate of #1443.

**Comment by shahinism** [comment] 2020-05-16 18:18
> @shahinism Thank you for reporting this! Which database were you connecting to?

I use it with Spark, however as described above, I just invoked `--version` command and it failed.

**Closed as completed** 2020-05-20 16:37 UTC
Labels: bug
