### ISSUE TITLE
CondaVerificationError when installing conda-forge/win-64::great-expectations-0.8.6-py37_0 version

### ISSUE THREAD

**Issue by owen-synergy** [fivetran/great_expectations#963] opened 2020-01-08 07:31 UTC
I'm attempting to install the conda-forge version of great-expectations (version 0.8.6) on Windows 10 and receive the following errors:

```
CondaVerificationError: The package for great-expectations located at C:\Users\307357\AppData\Local\Continuum\miniconda3\pkgs\great-expectations-0.8.6-py37_0
appears to be corrupted. The path 'Lib/site-packages/tests/data_context/fixtures/post_init_project_v0.8.0_A/great_expectations/uncommitted/documentation/local_site/expectations/data__dir/default/bob-ross/BasicDatasetProfiler.html'
specified in the package manifest cannot be found.

CondaVerificationError: The package for great-expectations located at C:\Users\307357\AppData\Local\Continuum\miniconda3\pkgs\great-expectations-0.8.6-py37_0
appears to be corrupted. The path 'Lib/site-packages/tests/data_context/fixtures/post_init_project_v0.8.0_A/great_expectations/uncommitted/documentation/local_site/profiling/data__dir/default/bob-ross/BasicDatasetProfiler.html'
specified in the package manifest cannot be found.

CondaVerificationError: The package for great-expectations located at C:\Users\307357\AppData\Local\Continuum\miniconda3\pkgs\great-expectations-0.8.6-py37_0
appears to be corrupted. The path 'Lib/site-packages/tests/data_context/fixtures/post_init_project_v0.8.0_A/great_expectations/uncommitted/documentation/team_site/expectations/data__dir/default/bob-ross/BasicDatasetProfiler.html'
specified in the package manifest cannot be found.

CondaVerificationError: The package for great-expectations located at C:\Users\307357\AppData\Local\Continuum\miniconda3\pkgs\great-expectations-0.8.6-py37_0
appears to be corrupted. The path 'Lib/site-packages/tests/data_context/fixtures/post_init_project_v0.8.0_A/great_expectations/uncommitted/validations/profiling/data__dir/default/bob-ross/BasicDatasetProfiler.json'
specified in the package manifest cannot be found.
```

**Comment by owen-synergy** [comment] 2020-01-08 07:34
I've tried clearing my conda cache and reinstalling but seem to get this error consistently. Tried it in an empty conda environment too and also ran into the same issue.

**Comment by jcampbell** [comment] 2020-01-08 14:21
Thanks for letting me know--this sounds like there may just be a packaging issue and I'll look at it right now.

**Comment by jcampbell** [comment] 2020-01-08 22:46
I'm not sure I can completely replicate this yet. For clarity: what version of python are you using? Are you running via WSL or directly on Win10?

**Comment by owen-synergy** [comment] 2020-01-09 01:02
I'm using Python 3.7.6 on Windows directly (conda-forge is set as the top priority channel) - not WSL. Windows version (according to [System.Environment]::OSVersion.Version) is:

```
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      17763  0
```

I tried creating a new environment with the command:

conda create -n test_env python=3.7 great-expectations

and that still produces the same error. I am attempting to install on a corporate machine (but I do have local admin). Not sure if some other privilege could be interfering. I've had no issues with most other conda packages.

**Comment by jcampbell** [comment] 2020-01-09 15:38
I just spun up a completely fresh windows 10 build 17763 machine, installed anaconda, and installed great-expectations from conda-forge; I can't replicate that error yet. Now, there are a few odd things I noticed:

(1) tests/ is packaged in site_packages directly. conceptually this makes sense, but it's probably not a good practice for packaging.
(2) the default version of ge retrieved for python 3.8 was 0.6.x (0.6.1 I think) instead of 0.8.6; it correctly got 0.8.6 when I specified python 3.7

One thought is that you might need to update conda itself. But still, I wonder whether there's something going on upstream of your cache that is causing this problem...

If you'd like to set up a call and do a quick in-person troubleshoot, I'd be happy to do that. Ping me in our slack? (https://greatexpectations.io/slack)

**Comment by owen-synergy** [comment] 2020-01-10 01:41
Thanks very much for the detailed feedback. I'll try to reproduce on my home Windows machine and see what I find there first. I'll let you know how that goes and if I can't reproduce it there I guess we can close this issue. If it is specific to my environment I'll definitely reach out on Slack.

**Comment by owenlamont** [comment] 2020-01-11 03:31
Hi @jcampbell I installed great-expectations no problem on my home Windows machine (same conda version and environment location)... must be some funny configuration on my work laptop. Feel free to close this issue.

**Closed as completed** 2020-01-13 01:51 UTC

**Comment by LiRogers** [comment] 2020-01-14 14:49
If anyone else has this problem, it seems to be caused by the maximum path length in windows (260 characters). The file path to the BasicDatasetProfiler.html file even within the great-expectations package is over 200 characters, so if the location of your package cache is quite long the file can't be read.

I solved it by moving my package cache to a location with a shorter path

**Comment by owen-synergy** [comment] 2020-01-15 00:28
Good to know - I realised that my home Windows box environment location wasn't the same folder and it probably was a shorter path.
