### ISSUE TITLE
Unable to install GE on Cloud Composer cluster

### ISSUE THREAD

**Issue by jruokola** [fivetran/great_expectations#4113] opened 2022-02-02 13:27 UTC
Version conflicts with the newest GE version and cloud composer 2.0.2 airflow 2.1.4
```
Failed to install PyPI packages. black 22.1.0 has requirement click>=8.0.0, but you have click 7.1.2.
 Check the Cloud Build log at https://console.cloud.google.com/cloud-build/builds/86edd2ea-09f9-44fb-adff-ffac15d5cc2b?project=427665163432 for details. For detailed instructions see https://cloud.google.com/composer/docs/troubleshooting-package-installation
```
apache-beam installation requires click < 8.0.0 and black>=8.0.0
Tried installing the following
pybigquery>=0.10.2
great-expectations>=0.14.4

**Comment by kenwade4** [comment] 2022-02-02 17:11
Closing since this appears to be a duplicate of https://github.com/great-expectations/great_expectations/issues/4106

**Closed as completed** 2022-02-02 17:11 UTC
