### ISSUE TITLE
Tutorial is broken

### ISSUE THREAD

**Issue by lucasvw** [fivetran/great_expectations#2359] opened 2021-02-01 10:46 UTC
**Describe the bug**
When following the "Getting started with Great Expectations" [tutorial](https://docs.greatexpectations.io/en/latest/guides/tutorials/getting_started.html), the step where you have to 

[Let’s execute all the cells and wait for Great Expectations to open a browser window with Data Docs. Pause here to read on first and find out what just happened!
](https://docs.greatexpectations.io/en/latest/guides/tutorials/getting_started/create_your_first_expectations.html) doesn't work and throws an error: 

`DataContextError: No validation operator 'action_list_operator' was found in your project. Please verify this in your great_expectations.yml`

When looking at the [`great_expectations.yml`](https://github.com/superconductive/ge_tutorials/blob/main/ge_getting_started_tutorial/great_expectations/great_expectations.yml) in the repo, it seems to be some versioning issue with missing `validation_operators` key. The version of the config in the repo is 2.0 and the version that you create during the tutorial is version 3.0 (which doesn't have this `validation_operators` key)

Once I added that block, I received a deprecation warning in the jupyter notebook but the code ran through and the data_docs page was created and opened.

**Comment by eugmandel** [comment] 2021-02-01 20:21
@lucasvw Thank you for reporting this! I will mark this issue as a duplicate of https://github.com/great-expectations/great_expectations/issues/2358 and close it. The core team will adjust the tutorial to use the updated APIs.

**Closed as completed by eugmandel** 2021-02-01 20:21 UTC
Labels: documentation
