### ISSUE TITLE
Error with Columns in Pandas - CSV file without headers

### ISSUE THREAD

**Issue by jkoput-b** [fivetran/great_expectations#6402] opened 2022-11-19 17:51 UTC
When using pandas with great expectations, using a .csv file without headers, I receive an error/exception that the column does not exist.  

**To Reproduce:**
### Setup a pandas datasource via GCS bucket using a .csv file that has no headers, i.e., 

123,"{""item"": false}"
325,"{""item"": false}"
258,"{""item"": false}"
125,"{""item"": false}"
258,"{""item"": false}"

### Setup an expectation
```
{
  "expectation_type": "expect_column_values_to_be_json_parseable",
  "ge_cloud_id": null,
  "kwargs": {
    "column": "0"
  }
}

```
### use pass through to make sure header is not set
```
"batch_spec_passthrough": {
    "reader_options": {
        "delimiter": ",",
        "header": None,
        "index_col": False,
        "usecols": [0, 1],
    }
}
```

The error that comes back is: (our directory is removed (and replaced with <airflow>)

```
Error: The column "0" in BatchData does not exist.
Traceback (most recent call last):
File "/opt/conda/envs/<airflow>/lib/python3.10/site-packages/great_expectations/execution_engine/execution_engine.py", line 393, in resolve_metrics
resolved_metrics[metric_to_resolve.id] = metric_fn(
File "/opt/conda/envs/<airflow>/lib/python3.10/site-packages/great_expectations/expectations/metrics/metric_provider.py", line 55, in inner_func
return metric_fn(*args, **kwargs)
File "/opt/conda/envs/<airflow>/lib/python3.10/site-packages/great_expectations/expectations/metrics/map_metric_provider.py", line 322, in inner_func
raise ge_exceptions.InvalidMetricAccessorDomainKwargsKeyError(
great_expectations.exceptions.exceptions.InvalidMetricAccessorDomainKwargsKeyError: Error: The column "0" in BatchData does not exist.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/opt/conda/envs/<airflow>/lib/python3.10/site-packages/great_expectations/validator/validator.py", line 1287, in resolve_validation_graph
self._resolve_metrics(
File "/opt/conda/envs/<airflow>/lib/python3.10/site-packages/great_expectations/validator/validator.py", line 2210, in _resolve_metrics
return execution_engine.resolve_metrics(
File "/opt/conda/envs/<airflow>/lib/python3.10/site-packages/great_expectations/execution_engine/execution_engine.py", line 397, in resolve_metrics
raise ge_exceptions.MetricResolutionError(
great_expectations.exceptions.exceptions.MetricResolutionError: Error: The column "0" in BatchData does not exist.
```

**Expected behavior**
It is expected to find the column but fail the expectation - the json is in column 1 but I was trying to get the item to work

Working with support via slack, I was able to get it to work via a work-around:
```
"batch_spec_passthrough": {
    "reader_options": {
        "delimiter": ",",
        "header": None,
        "index_col": False,
        "usecols": [0, 1],
        "names": ["0", "1"]
    }
},
```

Support said that I could also use "names": ["col1", "col2"] 

***BUT*** I cannot use string names -> that causes additional errors where the values are not allocated correctly (i.e. it sees column 0 (id) as column 1 (json) ) and fails the expectation(s)

**Environment (please complete the following information):**
 - Operating System: MacOS Ventura, using Docker; docker running debian 10.2 
 - Great Expectations Version:  "0.13.43"

**Comment by austiezr** [comment] 2022-12-01 18:36
Hey @jkoput-b ! Thanks for reaching out. Are you able to share the additional errors you're encountering? I'm unable to reproduce the behavior you're experiencing.

**Comment by jkoput-b** [comment] 2022-12-02 16:51
Hello,

I am not sure what else you need.  I can update that my Great Expectations version was actually 0.15.25 locally and 0.15.34 on GCP.  Both are having issues using a headerless CSV file.

The provider was 0.1.5 on both systems, and PANDAS was 1.3.5 on both systems as well.

Using just :

```
batch_request = {
    "datasource_name": "my_datasource",
    "data_connector_name": "default_inferred_data_connector_name",
    "batch_spec_passthrough": {
        "reader_options": {
            "header": None
        }
    }
}

```
with 
```
"kwargs": {
  "column": "1"
}
```



in the great expectations (as support told me was possible)  causes an error:
```
"exception_message": "Error: The column \"1\" in BatchData does not exist.",
        "exception_traceback": "Traceback (most recent call last):\n  File \"/opt/conda/envs/bairflow-af2-gke/lib/python3.10/site-packages/great_expectations/execution_engine/execution_engine.py\", line 407, in resolve_metrics\n    resolved_metrics[metric_to_resolve.id] = metric_fn(\n  File \"/opt/conda/envs/bairflow-af2-gke/lib/python3.10/site-packages/great_expectations/expectations/metrics/metric_provider.py\", line 55, in inner_func\n    return metric_fn(*args, **kwargs)\n  File \"/opt/conda/envs/bairflow-af2-gke/lib/python3.10/site-packages/great_expectations/expectations/metrics/map_metric_provider.py\", line 322, in inner_func\n    raise ge_exceptions.InvalidMetricAccessorDomainKwargsKeyError(\ngreat_expectations.exceptions.exceptions.InvalidMetricAccessorDomainKwargsKeyError: Error: The column \"1\" in BatchData does not exist.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/opt/conda/envs/bairflow-af2-gke/lib/python3.10/site-packages/great_expectations/validator/validation_graph.py\", line 178, in resolve_validation_graph\n    self._execution_engine.resolve_metrics(\n  File \"/opt/conda/envs/bairflow-af2-gke/lib/python3.10/site-packages/great_expectations/execution_engine/execution_engine.py\", line 411, in resolve_metrics\n    raise ge_exceptions.MetricResolutionError(\ngreat_expectations.exceptions.exceptions.MetricResolutionError: Error: The column \"1\" in BatchData does not exist.\n",
```

So, I am forced to use names:

```
"batch_spec_passthrough": {
    "reader_options": {
        "delimiter": ",",
        "header": None,
        "index_col": False,
        "usecols": [0, 1],
        "names": ["0", "1"]
    }
},
```

but when it runs on 0.15.34, the names are re-sorted so that they are seen as `"names": ['1', '0'] `
causing the expectations to fail.

```

"batch_spec": {
      "data_asset_name": "export_file",
      "path": "gs://<redacted>/<filename>.csv",
      "reader_options": {
        "delimiter": ",",
        "engine": "python",
        "header": null,
        "index_col": null,
        "usecols": [0, 1],
        "names": [
          "1",
          "0"
        ]
      }
```

**Comment by jkoput-b** [comment] 2022-12-13 19:28
Please note - we have deployed this with the column checks transposed (referring to column 0 as 1 and column 1 as 0) to get the expectations working.  After 5 days, the names value has suddenly started sorting back to: 

```
"names":  [
"0",
"1"
]
```

causing the code to break once again - this is with no changes in the version or the code - still on 0.15.35.

**Comment by austiezr** [comment] 2023-06-21 16:17
Hey @jkoput-b -- after many attempts to reproduce with various versions & configs, I'm unable to do so. If you're able to provide a complete script that reliably reproduces this behavior on a clean install, I may be able to hone in on what is happening here; otherwise, I can only think that there must be some transient quirk of your environment that I'm unable to identify, rather than something intrinsic to GX. Closing this out for now, but if you're able to provide above, please feel free to re-open! 🙇

**Closed as completed by austiezr** 2023-06-21 16:17 UTC
Labels: community, devrel
