### ISSUE TITLE
Lowercase table names in Snowflake are unreachable for SqlAlchemyDataset

### ISSUE THREAD

**Issue by Vfisa** [fivetran/great_expectations#1901] opened 2020-09-17 17:33 UTC
I am trying to use SQLAlchemy and Great Expectations for testing data quality of datasets stored in Snowflake DB in containerized environment. The dataset is called candidates and the column of interest is called first_name.
However, when I run
```
sql_dataset = great_expectations.dataset.SqlAlchemyDataset(table_name="candidates", engine=engine, schema=creds["schema"])
sql_dataset.expect_column_values_to_be_in_set("first_name", ['Gather', 'Male'])
```   
I am getting:
```
ProgrammingError: (snowflake.connector.errors.ProgrammingError) 002003 (42S02): SQL compilation error:
Object 'KEBOOLA_274.WORKSPACE_48777448.CANDIDATES' does not exist or not authorized.
[SQL: SELECT count(*) AS element_count, sum(CASE WHEN (first_name IS NULL) THEN %(param_1)s ELSE %(param_2)s END) AS null_count, sum(CASE WHEN (first_name NOT IN (%(first_name_1)s, %(first_name_2)s) AND first_name IS NOT NULL) THEN %(param_3)s ELSE %(param_4)s END) AS unexpected_count 
FROM "WORKSPACE_48777448".candidates]
[parameters: {'param_1': 1, 'param_2': 0, 'first_name_1': 'Gather', 'first_name_2': 'Male', 'param_3': 1, 'param_4': 0}]
(Background on this error at: http://sqlalche.me/e/13/f405)
```

The issue is the table name is not enclosed in double quotes, hence Snowflake is looking for CANDIDATES instead of candidates. The same issue would arise with the column name should the table be found.
I've tested
```
sql_dataset = great_expectations.dataset.SqlAlchemyDataset(table_name="\"candidates\"",
                                                           engine=engine,
                                                           schema=creds["schema"])
```
but Snowflake is then looking for a table called `KEBOOLA_274.WORKSPACE_48777448.""candidates"".`
I know SQLAlchemy by default considers lowercase object names to be case insensitive, therefore it doesn't enclose the names.

The only workaround we came up with was to uppercase the table first before using GE

also posted here: https://stackoverflow.com/questions/63827898/great-expectations-sqlalchemy-doesnt-enclose-lowercase-column-names

**Comment by spbail** [comment] 2020-09-17 19:09
Thanks for filing the issue! We'll review and respond!

**Comment by eugmandel** [comment] 2020-10-02 05:10
@Vfisa The core team triaged this bug and added to our queue. We will get to it shortly. Again, thank you for reporting this!

**Comment by talagluck** [comment] 2020-10-27 14:02
Hi @Vfisa! 

We were having trouble reproducing the issue on great_expectations version 0.12.6, sql_alchemy 1.3.18, and snowflake-sqlalchemy 1.2.3. Since we can't reproduce this, we are going to close this for now, but please let us know the versions you're using, and we can re-open if necessary.

**Comment by talagluck** [comment] 2020-10-30 13:16
On re-review, we were able to reproduce the issue, and are looking into whether a fix is possible. Stay tuned!

**Comment by eugmandel** [comment] 2020-11-30 23:54
PR https://github.com/great-expectations/great_expectations/pull/2023 was released with the release https://github.com/great-expectations/great_expectations/releases/tag/0.12.8 and addressed this issue

**Closed as completed by eugmandel** 2020-11-30 23:54 UTC
Labels: bug, stack:snowflake
