### ISSUE TITLE
Expectation gallery entry for expect_column_pair_values_a_to_be_greater_than_b includes deprecated keyword argument 'allow_cross_type_comparisons'

### ISSUE THREAD

**Issue by cmck-cw** [fivetran/great_expectations#6834] opened 2023-01-19 13:25 UTC
**Describe the bug**
At the Expectation Gallery, `expect_column_pair_values_a_to_be_greater_than_b` the kwarg `allow_cross_type_comparisons` is still listed in the docs as a supported feature however this feature was deprecated as per: https://github.com/great-expectations/great_expectations/issues/3373

Using this kwarg throws NotImplementedError as per:
https://github.com/great-expectations/great_expectations/blob/e6983e0af17e1423517aa0456be53f403fa94b1a/great_expectations/expectations/metrics/column_pair_map_metrics/column_pair_values_greater.py#L41

Can this be removed from the docs?

**To Reproduce**
1. Navigate to: https://greatexpectations.io/expectations/expect_column_pair_values_a_to_be_greater_than_b
2. See listed supported keyword arguments

**Expected behavior**
1. `allow_cross_type_comparisons` not listed as a supported kwarg.

**Environment (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by austiezr** [comment] 2023-01-19 19:06
Hey @cmck-cw ! Thanks for raising this. Is this something you'd be interested in contributing on?

**Comment by anthonyburdi** [comment] 2023-05-24 17:47
Hi @cmck-cw, thank you for flagging this issue! We have reproduced and created a ticket to remove the relevant code per our [deprecation policy](https://docs.greatexpectations.io/docs/changelog/#deprecation-policy) since it has been deprecated since v0.13. I'll close this issue for now since we are tracking internally, but if this is something you'd like to contribute please reach out here or in our slack in #contributing (internal ticket for reference: [DX-565](https://greatexpectations.atlassian.net/browse/DX-565))

[DX-565]: https://greatexpectations.atlassian.net/browse/DX-565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Closed as completed by anthonyburdi** 2023-05-24 17:47 UTC
Labels: community, devrel
