### ISSUE TITLE
Expectation fails when trying to evaluate values from a column which stores values in form of arrays

### ISSUE THREAD

**Issue by vaidehid1305** [fivetran/great_expectations#3201] opened 2021-08-09 15:40 UTC
**Describe the bug**
I am trying to evaluate values in a table column which stores arrays. The expectation I am using is: "expect_column_values_to_not_be_in_set". The column I am evaluating has 'null,null' string values stored in few records and I am trying to filter them and find their count and percentages.

Below are the ways in which I tried to write this expectation:
batch.expect_column_values_to_not_be_in_set("robot_families", ['null','null'])
batch.expect_column_values_to_not_be_in_set("robot_families", [['null','null']])
batch.expect_column_values_to_not_be_in_set("robot_families", [{'null','null'}])

For all these syntaxes I get following error:

OperationalError: (pyathena.error.OperationalError) SYNTAX_ERROR: line 1:151: IN value and list items must be the same type: array(varchar(8))
[SQL: SELECT count(*) AS "element_count", sum(CASE WHEN ("robot_families" IS NULL) THEN %(param_1)s ELSE %(param_2)s END) AS "null_count", sum(CASE WHEN ("robot_families" IN ((%(robot_families_1_1_1)s)) AND "robot_families" IS NOT NULL) THEN %(param_3)s ELSE %(param_4)s END) AS "unexpected_count" 
FROM "hkc_cache"."user_master_record"]
[parameters: {'param_1': 1, 'param_2': 0, 'param_3': 1, 'param_4': 0, 'robot_families_1_1_1': 'null'}]
(Background on this error at: http://sqlalche.me/e/14/e3q8)

**To Reproduce**
1. Run the expectation expect_column_values_to_not_be_in_set with any column that stores array type of values

**Expected behavior**
Would like to know the syntax of evaluating array type of columns using this expectation.
Expected result set should contain unexpected count and percentage .

**Environment (please complete the following information):**
 - Operating System: Mac OS
 - Great Expectations Version:  0.13.20

**Additional context**

**Comment by talagluck** [comment] 2021-08-10 17:56
Thanks for submitting, @vaidehid1305 ! We will review internally and get back to you over the next week or so.

**Comment by austiezr** [comment] 2021-11-16 19:15
Hey @vaidehid1305! I'm working on reproducing and understanding this behavior right now.

I'm getting seeing succeeding behavior for your first case `batch.expect_column_values_to_not_be_in_set("robot_families", ['null','null'])` on a column of arrays testing against `'null'` entries;
similarly succeeding behavior on the same column testing against `'null,null'` entries with `batch.expect_column_values_to_not_be_in_set("robot_families", ['null,null'])`, but I need some more context to verify what is (or isn't) happening.

Would you be able to provide an example of the column you're testing against? To verify, are you intending to test against an array of `['null', 'null']`, an array of `['null,null']`, or a string of `'null,null'`?

**Comment by austiezr** [comment] 2021-11-23 19:24
Hey @vaidehid1305! As Athena isn't an officially supported backend and I'm unable to reproduce this behavior as described, I'm closing this for now. If you feel differently, or are able to provide further context, please do so!

**Closed as completed by austiezr** 2021-11-23 19:24 UTC
Labels: community, devrel
