### ISSUE TITLE
When adding a datasource CLI presents three duplicate warnings about `black`

### ISSUE THREAD

**Issue by Aylr** [fivetran/great_expectations#3757] opened 2021-11-29 22:12 UTC
**Describe the bug**

**To Reproduce**
1. Create a new project in a new python environment with only GE installed with `great_expectations --v3-api init`
2. Add a datasource with `great_expectations --v3-api datasource new`
3. Choose `Pandas`
4. add path to data files
5. Observe three warnings about black

**Expected behavior**
I'd expect only 1 warning, ideally with context on why a user would want linting.

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.13.44

**Comment by Aylr** [comment] 2021-11-29 22:15
Note on other commands this error is shown more than three times.

This was seen in profiling a new suite.

```
Please install the optional dependency 'black' to enable linting. Returning input with no changes.
Please install the optional dependency 'black' to enable linting. Returning input with no changes.
Please install the optional dependency 'black' to enable linting. Returning input with no changes.
Please install the optional dependency 'black' to enable linting. Returning input with no changes.
```

**Comment by austiezr** [comment] 2021-11-30 20:58
Hey @Aylr! Thanks for surfacing this; this is definitely unexpected behavior. We'll review internally and be in touch!

**Comment by cdkini** [comment] 2021-12-01 23:06
Hey @Aylr! Nice seeing you here 👋🏽 

The above PR should resolve the issue you're seeing; thanks for bringing it up! We're just refining things but should have the changes merged in shortly.

**Comment by cdkini** [comment] 2021-12-02 16:05
I'm going to close down this issue since the above PR should resolve the matter. Let me know if you're not seeing that on your side and I'm happy to re-open  🎉

**Closed as completed by cdkini** 2021-12-02 16:05 UTC
Labels: community, devrel
