### ISSUE TITLE
Checkpoints do not work with spark dataframes

### ISSUE THREAD

**Issue by alitsaberi** [fivetran/great_expectations#3678] opened 2021-11-15 13:08 UTC
Trying to run a checkpoint on a spark data frame, but I get the following error:
```---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/var/folders/4q/qc3xhr1x6qx5jr9604nl91w40000gn/T/ipykernel_31603/2678565747.py in <module>
----> 1 checkpoint_run_result = context.run_checkpoint(
      2     checkpoint_name="gps_test",
      3     batch_request={
      4         "runtime_parameters": {
      5             "batch_data": df,

~/miniforge3/lib/python3.8/site-packages/great_expectations/data_context/data_context.py in run_checkpoint(self, checkpoint_name, template_name, run_name_template, expectation_suite_name, batch_request, action_list, evaluation_parameters, runtime_configuration, validations, profilers, run_id, run_name, run_time, result_format, ge_cloud_id, expectation_suite_ge_cloud_id, **kwargs)
   3352         checkpoint_config.update(checkpoint_config_from_call_args)
   3353         if not self.ge_cloud_mode:
-> 3354             checkpoint_config = filter_properties_dict(
   3355                 properties=checkpoint_config, clean_falsy=True
   3356             )

~/miniforge3/lib/python3.8/site-packages/great_expectations/util.py in filter_properties_dict(properties, keep_fields, delete_fields, clean_nulls, clean_falsy, keep_falsy_numerics, inplace)
    965 
    966     if not inplace:
--> 967         properties = copy.deepcopy(properties)
    968 
    969     keys_for_deletion: list = []

~/miniforge3/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    144     copier = _deepcopy_dispatch.get(cls)
    145     if copier is not None:
--> 146         y = copier(x, memo)
    147     else:
    148         if issubclass(cls, type):

~/miniforge3/lib/python3.8/copy.py in _deepcopy_dict(x, memo, deepcopy)
    228     memo[id(x)] = y
    229     for key, value in x.items():
--> 230         y[deepcopy(key, memo)] = deepcopy(value, memo)
    231     return y
    232 d[dict] = _deepcopy_dict

~/miniforge3/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    144     copier = _deepcopy_dispatch.get(cls)
    145     if copier is not None:
--> 146         y = copier(x, memo)
    147     else:
    148         if issubclass(cls, type):

~/miniforge3/lib/python3.8/copy.py in _deepcopy_dict(x, memo, deepcopy)
    228     memo[id(x)] = y
    229     for key, value in x.items():
--> 230         y[deepcopy(key, memo)] = deepcopy(value, memo)
    231     return y
    232 d[dict] = _deepcopy_dict

~/miniforge3/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    144     copier = _deepcopy_dispatch.get(cls)
    145     if copier is not None:
--> 146         y = copier(x, memo)
    147     else:
    148         if issubclass(cls, type):

~/miniforge3/lib/python3.8/copy.py in _deepcopy_dict(x, memo, deepcopy)
    228     memo[id(x)] = y
    229     for key, value in x.items():
--> 230         y[deepcopy(key, memo)] = deepcopy(value, memo)
    231     return y
    232 d[dict] = _deepcopy_dict

~/miniforge3/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    170                     y = x
    171                 else:
--> 172                     y = _reconstruct(x, memo, *rv)
    173 
    174     # If is its own copy, don't memoize.

~/miniforge3/lib/python3.8/copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    268     if state is not None:
    269         if deep:
--> 270             state = deepcopy(state, memo)
    271         if hasattr(y, '__setstate__'):
    272             y.__setstate__(state)

~/miniforge3/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    144     copier = _deepcopy_dispatch.get(cls)
    145     if copier is not None:
--> 146         y = copier(x, memo)
    147     else:
    148         if issubclass(cls, type):

~/miniforge3/lib/python3.8/copy.py in _deepcopy_dict(x, memo, deepcopy)
    228     memo[id(x)] = y
    229     for key, value in x.items():
--> 230         y[deepcopy(key, memo)] = deepcopy(value, memo)
    231     return y
    232 d[dict] = _deepcopy_dict

~/miniforge3/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    170                     y = x
    171                 else:
--> 172                     y = _reconstruct(x, memo, *rv)
    173 
    174     # If is its own copy, don't memoize.

~/miniforge3/lib/python3.8/copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    268     if state is not None:
    269         if deep:
--> 270             state = deepcopy(state, memo)
    271         if hasattr(y, '__setstate__'):
    272             y.__setstate__(state)

~/miniforge3/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    144     copier = _deepcopy_dispatch.get(cls)
    145     if copier is not None:
--> 146         y = copier(x, memo)
    147     else:
    148         if issubclass(cls, type):

~/miniforge3/lib/python3.8/copy.py in _deepcopy_dict(x, memo, deepcopy)
    228     memo[id(x)] = y
    229     for key, value in x.items():
--> 230         y[deepcopy(key, memo)] = deepcopy(value, memo)
    231     return y
    232 d[dict] = _deepcopy_dict

~/miniforge3/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    170                     y = x
    171                 else:
--> 172                     y = _reconstruct(x, memo, *rv)
    173 
    174     # If is its own copy, don't memoize.

~/miniforge3/lib/python3.8/copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    268     if state is not None:
    269         if deep:
--> 270             state = deepcopy(state, memo)
    271         if hasattr(y, '__setstate__'):
    272             y.__setstate__(state)

~/miniforge3/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    144     copier = _deepcopy_dispatch.get(cls)
    145     if copier is not None:
--> 146         y = copier(x, memo)
    147     else:
    148         if issubclass(cls, type):

~/miniforge3/lib/python3.8/copy.py in _deepcopy_dict(x, memo, deepcopy)
    228     memo[id(x)] = y
    229     for key, value in x.items():
--> 230         y[deepcopy(key, memo)] = deepcopy(value, memo)
    231     return y
    232 d[dict] = _deepcopy_dict

~/miniforge3/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    170                     y = x
    171                 else:
--> 172                     y = _reconstruct(x, memo, *rv)
    173 
    174     # If is its own copy, don't memoize.

~/miniforge3/lib/python3.8/copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    268     if state is not None:
    269         if deep:
--> 270             state = deepcopy(state, memo)
    271         if hasattr(y, '__setstate__'):
    272             y.__setstate__(state)

~/miniforge3/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    144     copier = _deepcopy_dispatch.get(cls)
    145     if copier is not None:
--> 146         y = copier(x, memo)
    147     else:
    148         if issubclass(cls, type):

~/miniforge3/lib/python3.8/copy.py in _deepcopy_dict(x, memo, deepcopy)
    228     memo[id(x)] = y
    229     for key, value in x.items():
--> 230         y[deepcopy(key, memo)] = deepcopy(value, memo)
    231     return y
    232 d[dict] = _deepcopy_dict

~/miniforge3/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    170                     y = x
    171                 else:
--> 172                     y = _reconstruct(x, memo, *rv)
    173 
    174     # If is its own copy, don't memoize.

~/miniforge3/lib/python3.8/copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    268     if state is not None:
    269         if deep:
--> 270             state = deepcopy(state, memo)
    271         if hasattr(y, '__setstate__'):
    272             y.__setstate__(state)

~/miniforge3/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    144     copier = _deepcopy_dispatch.get(cls)
    145     if copier is not None:
--> 146         y = copier(x, memo)
    147     else:
    148         if issubclass(cls, type):

~/miniforge3/lib/python3.8/copy.py in _deepcopy_dict(x, memo, deepcopy)
    228     memo[id(x)] = y
    229     for key, value in x.items():
--> 230         y[deepcopy(key, memo)] = deepcopy(value, memo)
    231     return y
    232 d[dict] = _deepcopy_dict

~/miniforge3/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    159                     reductor = getattr(x, "__reduce_ex__", None)
    160                     if reductor is not None:
--> 161                         rv = reductor(4)
    162                     else:
    163                         reductor = getattr(x, "__reduce__", None)

TypeError: cannot pickle '_thread.RLock' object
```
This is similar to #2905 and the issue was supposed to be resolved in release 0.13.38, but it still persists. I'm using 0.13.42.

**To Reproduce**
1. Configure a data context and a data source 
```datasources:
  datasource_name:
    data_connectors:
      default_runtime_data_connector_name:
        batch_identifiers:
          - batch_id
        class_name: RuntimeDataConnector
        module_name: great_expectations.datasource.data_connector
    class_name: Datasource
    execution_engine:
      class_name: SparkDFExecutionEngine
      module_name: great_expectations.execution_engine
    module_name: great_expectations.datasource
```
2- Configure a checkpoint
3- Create a Spark dataframe and run the checkpoint:
```
checkpoint_run_result = context.run_checkpoint(
    checkpoint_name="checkpoint_name",
    batch_request={
        "runtime_parameters": {
            "batch_data": df,
        }
    },
    run_name="Hello",
)
```

**Expected behavior**
I Expect the checkpoint to be run with no error.

**Environment:**
 - Operating System: MacOS
 - Great Expectations Version: 0.13.42
 - Spark Version: 3.2.0
 - Environment: Jupyter Notebook

**Comment by talagluck** [comment] 2021-11-15 19:42
Thanks for raising this issue, @alit8! I believe this is a duplicate of #3551, and a bugfix is currently in process. Since this is a duplicate, I'll close this for now, but please feel free to re-open if you feel differently.

**Closed as completed by talagluck** 2021-11-15 19:42 UTC
Labels: community, devrel

**Comment by NathanFarmer** [comment] 2021-11-17 14:12
Hi @alit8, using `RuntimeBatchRequest`s in `Checkpoint`s is under development in the current sprint. You should be able to get around this for now by passing the batch request into a `Checkpoint` object using `validations`. Open PR #3680 addresses passing the `RuntimeBatchRequest` into a `Checkpoint` object instead of into `context.run_checkpoint`.

**Comment by dbeswick-bupa** [comment] 2021-11-30 23:19
Hello @NathanFarmer , I've just tested this with 0.13.44 and unfortunately I still get the same problem.

[traceback.txt](https://github.com/great-expectations/great_expectations/files/7629481/traceback.txt)
[ge-3494.txt](https://github.com/great-expectations/great_expectations/files/7629493/ge-3494.txt)

**Comment by NathanFarmer** [comment] 2021-12-01 21:35
Hi @dbeswick-bupa, I see two problems with your code:

1. You want to unpack your checkpoint config dictionary by adding `**` in the `add_checkpoint` command: `context.add_checkpoint(**cfg_checkpoint)`
2. With the latest version of GE (0.13.44), you will get an error message stating that `InvalidConfigError: batch_data found in validations at index 0 cannot be saved to CheckpointStore "checkpoint_store"`. Instead of saving the DataFrame to your `CheckpointStore`, you will want to pass it in during the `context.run_checkpoint()` command. Documentation on this is hot off the presses: [How to pass an in-memory DataFrame to a Checkpoint](https://docs.greatexpectations.io/docs/guides/validation/checkpoints/how_to_pass_an_in_memory_dataframe_to_a_checkpoint)

**Comment by dbeswick-bupa** [comment] 2021-12-01 23:58
My apologies Nathan, thanks for the corrections and for the pointers to the right information! My sample also had other issues. This is working for me after following the instructions on that page.

I've attached my corrected code in case someone finds it useful.

[ge-3494-2.txt](https://github.com/great-expectations/great_expectations/files/7637851/ge-3494-2.txt)
