### ISSUE TITLE
Error running action with name send_slack_notification_on_validation_result: TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by NiallRees** [fivetran/great_expectations#1909] opened 2020-09-19 09:31 UTC
**Describe the bug**
An error with send_slack_notification_on_validation_result. Occurring every time there's a validation fail and a slack alert attempts to be sent off. I'm using S3 data docs.

```
ERROR:great_expectations.validation_operators.validation_operators:Error running action with name send_slack_notification_on_validation_result
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/great_expectations/validation_operators/validation_operators.py", line 383, in _run_actions
    payload=batch_actions_results,
  File "/usr/local/lib/python3.7/site-packages/great_expectations/validation_operators/actions.py", line 50, in run
    **kwargs
  File "/usr/local/lib/python3.7/site-packages/great_expectations/validation_operators/actions.py", line 162, in _run
    query = self.renderer.render(validation_result_suite, data_docs_pages)
  File "/usr/local/lib/python3.7/site-packages/great_expectations/render/renderer/slack_renderer.py", line 63, in render
    if "file:///" in docs_link:
TypeError: argument of type 'NoneType' is not iterable
```

**To Reproduce**
I'm not too sure, this has just started happening with no other change.

**Environment (please complete the following information):**
GE version 0.12.1

Perhaps linked - our data docs have stopped updating.

**Comment by eugmandel** [comment] 2020-09-22 15:28
Thank you for reporting this, @NiallRees ! We will triage and respond within a couple of days.

**Comment by NiallRees** [comment] 2020-09-22 15:40
I fixed this issue by deleting the contents of the s3 bucket and rebuilding the docs. I'll let you know if it occurs again @eugmandel

**Comment by NiallRees** [comment] 2020-09-24 19:04
Perhaps also related this error has just started on all our scheduled GE checks:

```
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    context.build_data_docs()
  File "/usr/local/lib/python3.7/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 257, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/great_expectations/data_context/data_context.py", line 1573, in build_data_docs
    resource_identifiers
  File "/usr/local/lib/python3.7/site-packages/great_expectations/render/renderer/site_builder.py", line 292, in build
    index_page_resource_identifier_tuple = self.site_index_builder.build()
  File "/usr/local/lib/python3.7/site-packages/great_expectations/render/renderer/site_builder.py", line 769, in build
    ].remove_key(validation_result_site_key)
  File "/usr/local/lib/python3.7/site-packages/great_expectations/data_context/store/tuple_store_backend.py", line 537, in remove_key
    s3_object_key = self._build_s3_object_key(key)
  File "/usr/local/lib/python3.7/site-packages/great_expectations/data_context/store/tuple_store_backend.py", line 403, in _build_s3_object_key
    s3_object_key = self._convert_key_to_filepath(key)
  File "/usr/local/lib/python3.7/site-packages/great_expectations/data_context/store/tuple_store_backend.py", line 86, in _convert_key_to_filepath
    self._validate_key(key)
  File "/usr/local/lib/python3.7/site-packages/great_expectations/data_context/store/tuple_store_backend.py", line 64, in _validate_key
    super()._validate_key(key)
  File "/usr/local/lib/python3.7/site-packages/great_expectations/data_context/store/store_backend.py", line 72, in _validate_key
    self.__class__.__name__, tuple, type(key),
TypeError: Keys in TupleS3StoreBackend must be instances of <class 'tuple'>, not <class 'great_expectations.data_context.types.resource_identifiers.ValidationResultIdentifier'>
```

**Comment by eugmandel** [comment] 2020-10-01 14:44
@NiallRees Your latest comment refers to this bug: https://github.com/great-expectations/great_expectations/issues/1907.
We identified the root cause and will have a fix shortly.

**Comment by eugmandel** [comment] 2020-10-01 14:48
@NiallRees based on the fact that the error stopped happening after rebuilding the Data Docs on S3 and your latest comment that points to https://github.com/great-expectations/great_expectations/issues/1907, I want to close this issue.

If this comes back in a release that has the fix for https://github.com/great-expectations/great_expectations/issues/1907, we will re-open it.

**Closed as completed** 2020-10-01 14:48 UTC
