### ISSUE TITLE
GreatExpectations not providing schema to temp table creation in Snowflake

### ISSUE THREAD

**Issue by denimalpaca** [fivetran/great_expectations#7228] opened 2023-02-24 17:48 UTC
**Describe the bug**
When running Great Expectations on a Snowflake table, the SqlAlchemyEngine is throwing an error about not finding a schema in the current session. This was not an issue in `0.15.44` but is now an issue when I upgraded to `0.15.50`.

**To Reproduce**
Run Great Expectations with a Snowflake connection on a Snowflake table.

**Expected behavior**
Expect the expectation suite to create a temp table and run and succeed.

**Environment (please complete the following information):**
 - Operating System: Linux (Running on Astro runtime 7.3.0)
 - Great Expectations Version: `great-expectations==0.15.50`

**Additional context**
Stack trace:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/great_expectations_provider/operators/great_expectations.py", line 517, in execute
    result = self.checkpoint.run(batch_request=self.batch_request)
  File "/usr/local/lib/python3.9/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 318, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/great_expectations/checkpoint/checkpoint.py", line 250, in run
    self._run_validation(
  File "/usr/local/lib/python3.9/site-packages/great_expectations/checkpoint/checkpoint.py", line 404, in _run_validation
    validator: Validator = self.data_context.get_validator(
  File "/usr/local/lib/python3.9/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 2410, in get_validator
    self.get_batch_list(
  File "/usr/local/lib/python3.9/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 318, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 2577, in get_batch_list
    return self._get_batch_list(
  File "/usr/local/lib/python3.9/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 2654, in _get_batch_list
    return datasource.get_batch_list_from_batch_request(batch_request=batch_request)
  File "/usr/local/lib/python3.9/site-packages/great_expectations/datasource/new_datasource.py", line 214, in get_batch_list_from_batch_request
    ) = data_connector.get_batch_data_and_metadata(
  File "/usr/local/lib/python3.9/site-packages/great_expectations/datasource/data_connector/data_connector.py", line 119, in get_batch_data_and_metadata
    batch_data, batch_markers = self._execution_engine.get_batch_data_and_markers(
  File "/usr/local/lib/python3.9/site-packages/great_expectations/execution_engine/sqlalchemy_execution_engine.py", line 1290, in get_batch_data_and_markers
    batch_data = SqlAlchemyBatchData(
  File "/usr/local/lib/python3.9/site-packages/great_expectations/execution_engine/sqlalchemy_batch_data.py", line 161, in __init__
    self._create_temporary_table(
  File "/usr/local/lib/python3.9/site-packages/great_expectations/execution_engine/sqlalchemy_batch_data.py", line 295, in _create_temporary_table
    self._engine.execute(stmt)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1271, in execute
    return self._exec_driver_sql(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1575, in _exec_driver_sql
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2023, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1799, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.9/site-packages/snowflake/connector/cursor.py", line 827, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/usr/local/lib/python3.9/site-packages/snowflake/connector/errors.py", line 275, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/usr/local/lib/python3.9/site-packages/snowflake/connector/errors.py", line 330, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/usr/local/lib/python3.9/site-packages/snowflake/connector/errors.py", line 209, in default_errorhandler
    raise error_class(
sqlalchemy.exc.ProgrammingError: (snowflake.connector.errors.ProgrammingError) 090106 (22000): 01aa8c8e-0606-e34e-0000-682126158d46: Cannot perform CREATE TEMPTABLE. This session does not have a current schema. Call 'USE SCHEMA', or use a qualified name.
[SQL: CREATE OR REPLACE TEMPORARY TABLE ge_temp_7ccd7b66 AS SELECT * 
FROM "BENJI"."YELLOW_TRIPDATA_AUDIT" 
WHERE true]
(Background on this error at: https://sqlalche.me/e/14/f405)
```

**Comment by austiezr** [comment] 2023-03-01 16:26
Hey @denimalpaca ! Thanks for reaching out.

Are you able to share your DataContext configuration (with any PII removed), as well as the exact workflow generating this error? That will help us to better understand what may be happening here.

**Comment by denimalpaca** [comment] 2023-03-01 17:20
Hey @austiezr 

My entire DataContext config is this great_expectations.yml file:
```
# Welcome to Great Expectations! Always know what to expect from your data.
#
# Here you can define datasources, batch kwargs generators, integrations and
# more. This file is intended to be committed to your repo. For help with
# configuration please:
#   - Read our docs: https://docs.greatexpectations.io/en/latest/reference/spare_parts/data_context_reference.html#configuration
#   - Join our slack channel: http://greatexpectations.io/slack

# config_version refers to the syntactic version of this config file, and is used in maintaining backwards compatibility
# It is auto-generated and usually does not need to be changed.
config_version: 3.0

# Datasources tell Great Expectations where your data lives and how to get it.
# You can use the CLI command `great_expectations datasource new` to help you
# add a new datasource. Read more at https://docs.greatexpectations.io/en/latest/reference/core_concepts/datasource.html

# NOTE: Datasources in this repository are built on-the-fly by the GreatExpectationsOperator

# The plugins_directory will be added to your python path for custom modules
# used to override and extend Great Expectations.
plugins_directory: plugins/

stores:
# Stores are configurable places to store things like Expectations, Validations
# Data Docs, and more. These are for advanced users only - most users can simply
# leave this section alone.
#
# Three stores are required: expectations, validations, and
# evaluation_parameters, and must exist with a valid store entry. Additional
# stores can be configured for uses such as data_docs, etc.
  expectations_store:
    class_name: ExpectationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: expectations/

  validations_store:
    class_name: ValidationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/validations/

  evaluation_parameter_store:
    class_name: EvaluationParameterStore
  checkpoint_store:
    class_name: CheckpointStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: checkpoints/

expectations_store_name: expectations_store
validations_store_name: validations_store
evaluation_parameter_store_name: evaluation_parameter_store
checkpoint_store_name: checkpoint_store

data_docs_sites:
  # Data Docs make it simple to visualize data quality in your project. These
  # include Expectations, Validations & Profiles. The are built for all
  # Datasources from JSON artifacts in the local repo including validations &
  # profiles from the uncommitted directory. Read more at https://docs.greatexpectations.io/en/latest/reference/core_concepts/data_docs.html
  local_site:
    class_name: SiteBuilder
    show_how_to_buttons: true
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/data_docs/local_site/
    site_index_builder:
      class_name: DefaultSiteIndexBuilder

anonymous_usage_statistics:
  data_context_id: abcdabcd-1111-2222-3333-abcdabcdabcd
  enabled: false
notebooks:
concurrency:
  enabled: false
include_rendered_content:
  globally: false
  expectation_validation_result: false
  expectation_suite: false
```

which is pretty bare-bones, I'm not sure I did anything to update it after I created the project (a while ago, so that might also be an issue).

The workflow is using Great Expectations with Airflow, using the GreatExpecatationsOperator which creates a checkpoint internally (I'm not supplying one). It's using the schema that I either pass or that's found in the `conn_id` parameter, which uses my snowflake_default connection that _does_ have a schema. Neither of these methods works with the new GX version, but both work with the older version. The data source is added dynamically to the data context [here](https://github.com/astronomer/airflow-provider-great-expectations/blob/main/great_expectations_provider/operators/great_expectations.py#L493).

**Comment by billdirks** [comment] 2023-05-12 23:19
Hi @denimalpaca ,
Thanks for reporting this. I'm trying to recreate this issue using Great Expectations 0.15.50 and am not able to hit this. I'm following our [documentation for snowflake](https://docs.greatexpectations.io/docs/0.15.50/guides/connecting_to_your_data/database/snowflake/), explicitly setting `create_temp_table` to `true`, and using a non-public schema (see my code snippet below).

I checked the operator link you provided and I see it's building a `datasource_config` dictionary dynamically in code. Do you know if the operator code has changed recently? Could you share the `datasource_config` the operator produces (after removing PII)? I believe, the telling item may be the form connection configuration.

Here is my code snippet below which succeeds in `0.15.50`:

```
import os
from ruamel import yaml

import great_expectations as gx
from great_expectations.core.batch import BatchRequest, RuntimeBatchRequest

sfAccount = os.environ.get("SNOWFLAKE_ACCOUNT")
sfUser = os.environ.get("SNOWFLAKE_USER")
sfPswd = os.environ.get("SNOWFLAKE_PW")
sfDatabase = os.environ.get("SNOWFLAKE_DATABASE")
sfSchema = os.environ.get("SNOWFLAKE_SCHEMA")
sfWarehouse = os.environ.get("SNOWFLAKE_WAREHOUSE")
sfTableName=os.environ.get("SNOWFLAKE_TABLE_NAME")

CONNECTION_STRING = f"snowflake://{sfUser}:{sfPswd}@{sfAccount}/{sfDatabase}/{sfSchema}?warehouse={sfWarehouse}&application=great_expectations_oss"

context = gx.get_context()

datasource_yaml = f"""
name: my_snowflake_datasource
class_name: Datasource
execution_engine:
  class_name: SqlAlchemyExecutionEngine
  connection_string: snowflake://<USER_NAME>:<PASSWORD>@<ACCOUNT_NAME>/<DATABASE_NAME>/<SCHEMA_NAME>?warehouse=<WAREHOUSE_NAME>&role=<ROLE_NAME>&application=great_expectations_oss
  create_temp_table: true
data_connectors:
   default_runtime_data_connector_name:
       class_name: RuntimeDataConnector
       batch_identifiers:
           - default_identifier_name
   default_inferred_data_connector_name:
       class_name: InferredAssetSqlDataConnector
       include_schema_name: true
"""
datasource_yaml = datasource_yaml.replace(
    "snowflake://<USER_NAME>:<PASSWORD>@<ACCOUNT_NAME>/<DATABASE_NAME>/<SCHEMA_NAME>?warehouse=<WAREHOUSE_NAME>&role=<ROLE_NAME>&application=great_expectations_oss",
    CONNECTION_STRING,
)

# Print diagnostic information
context.test_yaml_config(datasource_yaml)

context.add_or_update_datasource(**yaml.load(datasource_yaml))

batch_request = RuntimeBatchRequest(
    datasource_name="my_snowflake_datasource",
    data_connector_name="default_runtime_data_connector_name",
    data_asset_name="default_name",
    runtime_parameters={
        "query": f"SELECT * from {sfSchema.lower()}.{sfTableName} LIMIT 10"
    },
    batch_identifiers={"default_identifier_name": "default_identifier"},
)

context.add_or_update_expectation_suite(expectation_suite_name="test_suite")
validator = context.get_validator(
    batch_request=batch_request, expectation_suite_name="test_suite"
)
print(validator.head(3))
```

**Comment by anthonyburdi** [comment] 2023-05-24 13:59
Hi @denimalpaca, I'm just following up on the above comment from Bill, would you be able to share the `datasource_config` that the operator produces?

**Comment by anthonyburdi** [comment] 2023-05-24 14:06
For now I'm going to close this issue since we were unable to reproduce but please feel free to reopen or create a new issue if this is still persisting. Thank you!

**Closed as completed by anthonyburdi** 2023-05-24 14:06 UTC
Labels: community, devrel
