### ISSUE TITLE
Wrong results with expect_column_kl_divergence_to_be_less_than

### ISSUE THREAD

**Issue by kpongracic** [fivetran/great_expectations#6527] opened 2022-12-09 09:27 UTC
**Describe the bug**
When using `expect_column_kl_divergence_to_be_less_than` with the spark data frame I get the wrong results. This happens only if values are float numbers, in my case I use decimal(30,6) and decimal(6,2). I use the same expectation on `bigint` and `string` columns and they work fine. The problem is that in `values` under `expected_partition` and `observed_partition` I get a copy of the same number and then the `weights` of one is good as defined in the expectation but the other value is 0, resulting in `observed_value ` of the test to be `null`. Here is the example I used, as you can see the problem is with`0.01`, `0.1`, and `1.01`, but as you can see the `values` under `expectation_config` don't have copies:

```
"results": [
    {
      "exception_info": {
        "exception_message": null,
        "exception_traceback": null,
        "raised_exception": false
      },
      "expectation_config": {
        "expectation_type": "expect_column_kl_divergence_to_be_less_than",
        "kwargs": {
          "batch_id": "78b85baa14900df246c24f30f078685a",
          "column": "PreviousStakeValue",
          "partition_object": {
            "values": [
              1.01,
              2.0,
              1.0,
              5.0,
              3.0,
              10.0,
              0.5,
              0.25,
              0.75,
              0.01,
              20.0,
              0.1,
              50.0,
              100.0
            ],
            "weights": [
              0.6390637918972206,
              0.19484195128156204,
              0.07053361317814666,
              0.041944921452648984,
              0.02254658780131018,
              0.012434013865038479,
              0.004960885327227629,
              0.004165871652992432,
              0.0027030464923996694,
              0.0021306366469503275,
              0.0018762322711950645,
              0.0016536284424092094,
              0.0009540164090822362,
              0.00019080328181644724
            ]
          },
          "threshold": 0.5
        },
        "meta": {}
      },
      "meta": {},
      "result": {
        "details": {
          "expected_partition": {
            "values": [
              0.01,
              0.01,
              0.1,
              0.1,
              0.25,
              0.5,
              0.75,
              1.0,
              1.01,
              1.01,
              2.0,
              3.0,
              5.0,
              10.0,
              20.0,
              50.0,
              100.0
            ],
            "weights": [
              0.0,
              0.0021306366469503275,
              0.0,
              0.0016536284424092094,
              0.004165871652992432,
              0.004960885327227629,
              0.0027030464923996694,
              0.07053361317814666,
              0.0,
              0.6390637918972206,
              0.19484195128156204,
              0.02254658780131018,
              0.041944921452648984,
              0.012434013865038479,
              0.0018762322711950645,
              0.0009540164090822362,
              0.00019080328181644724
            ]
          },
          "observed_partition": {
            "values": [
              0.01,
              0.01,
              0.1,
              0.1,
              0.25,
              0.5,
              0.75,
              1.0,
              1.01,
              1.01,
              2.0,
              3.0,
              5.0,
              10.0,
              20.0,
              50.0,
              100.0
            ],
            "weights": [
              0.0021306366469503275,
              0.0,
              0.0016536284424092094,
              0.0,
              0.004165871652992432,
              0.004960885327227629,
              0.0027030464923996694,
              0.07053361317814666,
              0.6390637918972206,
              0.0,
              0.19484195128156204,
              0.02254658780131018,
              0.041944921452648984,
              0.012434013865038479,
              0.0018762322711950645,
              0.0009540164090822362,
              0.00019080328181644724
            ]
          }
        },
        "observed_value": null
      },
      "success": false
    }
```

**To Reproduce**
1. Create a spark data frame with values that are shown above
2. Run`validator.expect_column_kl_divergence_to_be_less_than(col, distribution, 0.5)` and the results will be good
3. Save the expectation suite from `validator` and create a checkpoint
4. Run checkpoint and get wrong results ( `"observed_value": null` )

**Expected behavior**
No copies of values and expectations should be true, as it is when running on `bigint` and `string` types of columns

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.15.36

**Additional context**

**Comment by austiezr** [comment] 2022-12-12 16:59
Hey @kpongracic! Thanks for raising this; beginning to review this functionality.

**Comment by alexsherstinsky** [comment] 2023-06-05 22:49
Hello, @kpongracic -- sincere apologies for the delay.  I just became aware of this issue and would like to troubleshoot it together with you, if it is still relevant to your work.  In order to help me with this, could you please provide me the exact code that you used to run your scenario -- including, importantly, your dataset (minimal dataset to illustrate the problem).

Thank you very much in advance.  If convenient, please feel free to reach out in the GX Slack Community (and we will summarize the results of the troubleshooting here, once we are able to identify the cause of the problem).  Thanks a lot!

**Comment by alexsherstinsky** [comment] 2023-06-15 22:25
@kpongracic Hello, I will like to follow up on this -- hoping that you could please provide the information requested so that we can troubleshoot it.  Thanks very much.

**Comment by tyler-hoffman** [comment] 2023-06-21 18:03
Closing for now due to not hearing back in a week. Please feel feel free to reopen. Thanks!

**Closed as completed by tyler-hoffman** 2023-06-21 18:03 UTC
Labels: community, devrel
