### ISSUE TITLE
Unicode issues with init on Windows

### ISSUE THREAD

**Issue by jemmott** [fivetran/great_expectations#953] opened 2019-12-31 00:44 UTC
Running `great_expectations init` on Windows 10 command prompt I see `[36m` and similar.

![great](https://user-images.githubusercontent.com/43320559/71606160-71201880-2b23-11ea-8804-e5882b00d397.PNG)

I tried running it in Jupyter and got `UnicodeEncodeError: 'charmap' codec can't encode characters in position 138-140: character maps to <undefined>`

**Comment by Aylr** [comment] 2020-03-11 17:40
@jemmott I believe this was fixed in #1114 I'm going to close this - feel free to reopen it if you can't reproduce it!

**Closed as completed by Aylr** 2020-03-11 17:40 UTC

**Comment by jemmott** [comment] 2020-03-11 18:22
Confirmed fixed.  Great work!
