### ISSUE TITLE
[BUG] 'PandasDataset' object has no attribute 'expect_column_pair_values_a_to_be_greater_than_b'

### ISSUE THREAD

**Issue by grahamtyler** [fivetran/great_expectations#6242] opened 2022-10-28 15:13 UTC
**Describe the bug**
Executing the expect_column_pair_values_a_to_be_greater_than_b expectation on a dataframe results in the following error. This appears to be unique to this expectation, as other expectations execute correctly on the same dataframe using the same syntax. 

`AttributeError: 'PandasDataset' object has no attribute 'expect_column_pair_values_a_to_be_greater_than_b'`

**To Reproduce**
We import a Google Sheet with one row per expectation per column in the dataframe we want to evaluate using GE and one column for each relevant expectation input. We then cycle through each expectation:

```
def process_expectation(expectation: Series) -> namedtuple:
    # create named tuple with all possible arguments
    Args = namedtuple('Args', 'object expectation_type column mostly value value_set regex_list match_on min_value max_value strict_min strict_max column_b or_equal row_condition')
    
    # extract arguments from row (in Series format)
    obj = expectation['OBJECT']
    column = expectation['COLUMN'] if expectation['OBJECT'] == 'Contact' else expectation['OBJECT'] + '__' + expectation['COLUMN']
    expectation_type = expectation['EXPECTATION TYPE']
    mostly = expectation['MOSTLY']
    value = expectation['VALUE'] if pd.notna(expectation['VALUE']) else None
    value_set = set(expectation['VALUE SET'].splitlines()) if pd.notna(expectation['VALUE SET']) else None
    regex_list = set(expectation['REGEX LIST'].splitlines()) if pd.notna(expectation['REGEX LIST']) else None
    match_on = expectation['MATCH ON'] if pd.notna(expectation['MATCH ON']) else None
    min_value = expectation['MIN VALUE'] if pd.notna(expectation['MIN VALUE']) else None
    max_value = expectation['MAX VALUE'] if pd.notna(expectation['MAX VALUE']) else None
    strict_min = expectation['STRICT MIN'] if pd.notna(expectation['STRICT MIN']) else None
    strict_max = expectation['STRICT MAX'] if pd.notna(expectation['STRICT MAX']) else None
    column_b = expectation['COLUMN B'] if pd.notna(expectation['COLUMN B']) else None
    or_equal = expectation['OR EQUAL'] if pd.notna(expectation['OR EQUAL']) else None
    row_condition = expectation['ROW CONDITION'] if pd.notna(expectation['ROW CONDITION']) else None
    
    # instantiate named tuple and return it
    args = Args(obj, expectation_type, column, mostly, value, value_set, regex_list, match_on, min_value, max_value, strict_min, strict_max, column_b, or_equal, row_condition)
    
    return args
   
def set_expectations(data: PandasDataFrame, expectations: List[PandasDataFrame], suite_name: str) -> None:
    
    # load dataframe into GE df, to get instant feedback on set expectations
    data_ge = ge.from_pandas(data)
    

    for expectations_df in expectations:
        for index, expectation in expectations_df.iterrows():
            args = process_expectation(expectation)
            # required column
            if args.expectation_type == 'Required Column':
                data_ge.expect_column_to_exist(column=args.column)
                
            # non-null column
            elif args.expectation_type == 'Not Null':
                data_ge.expect_column_values_to_not_be_null(column=args.column, mostly=args.mostly, condition_parser='pandas', row_condition=args.row_condition)
                
            # date between
            elif args.expectation_type == 'Date Between':
                data_ge.expect_column_values_to_be_between(column=args.column, mostly=args.mostly,  min_value=args.min_value, max_value=args.max_value, strict_min=args.strict_min, strict_max=args.strict_max, condition_parser='pandas', row_condition=args.row_condition, parse_strings_as_datetimes=True)
                
            # value between
            elif args.expectation_type == 'Value Between':
                data_ge.expect_column_values_to_be_between(column=args.column, mostly=args.mostly,  min_value=args.min_value, max_value=args.max_value, strict_min=args.strict_min, strict_max=args.strict_max, condition_parser='pandas', row_condition=args.row_condition)
                
            # value in set
            elif args.expectation_type == 'In Value Set':
                data_ge.expect_column_values_to_be_in_set(column=args.column, mostly=args.mostly, value_set=args.value_set, condition_parser='pandas', row_condition=args.row_condition)
                
            # string matches regex
            elif args.expectation_type == 'String Match Regex':
                data_ge.expect_column_values_to_match_regex(column=args.column, regex=args.value, mostly=args.mostly, condition_parser='pandas', row_condition=args.row_condition)
            
            # string matches list of regex options
            elif args.expectation_type == 'Match Regex List':
                data_ge.expect_column_values_to_match_regex_list(column=args.column, regex_list=args.regex_list, match_on = args.match_on, mostly=args.mostly, condition_parser='pandas', row_condition=args.row_condition)
                
            # column A's values smaller than B's
            elif args.expectation_type == 'Column A Less Than Column B':
                data_ge.expect_column_pair_values_a_to_be_greater_than_b(column_A=args.column_b, column_B=args.column, or_equal=args.or_equal, mostly=args.mostly, condition_parser='pandas', row_condition=args.row_condition)
                
    # save expectations suite
    with open(ROOT_PYTHON + f"great_expectations/expectations/{suite_name}.json", "w") as my_file:
        my_file.write(
            json.dumps(data_ge.get_expectation_suite(discard_failed_expectations=False).to_json_dict())
        )
```

When executing the full function:
```
set_expectations(data=survey, expectations=expectations, suite_name=PROJECT_NAME)
```

We get this error: 

```
AttributeError: 'PandasDataset' object has no attribute 'expect_column_pair_values_a_to_be_greater_than_b'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<command-384786412766625> in <module>
----> 1 set_expectations(data=survey, expectations=expectations, suite_name=PROJECT_NAME)

<command-384786412766623> in set_expectations(data, expectations, suite_name)
     65             # column A's values smaller than B's
     66             elif args.expectation_type == 'Column A Less Than Column B':
---> 67                 data_ge.expect_column_pair_values_a_to_be_greater_than_b(column_A=args.column_b, column_B=args.column, or_equal=args.or_equal, mostly=args.mostly, condition_parser='pandas', row_condition=args.row_condition)
     68 
     69     # save expectations suite

/databricks/python/lib/python3.8/site-packages/pandas/core/generic.py in __getattr__(self, name)
   5463             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5464                 return self[name]
-> 5465             return object.__getattribute__(self, name)
   5466 
   5467     def __setattr__(self, name: str, value) -> None:

AttributeError: 'PandasDataset' object has no attribute 'expect_column_pair_values_a_to_be_greater_than_b'`

**Expected behavior**
Commenting out the code that calls this single expectation (below) results in the function running correctly and all other expectations being executed correctly. 
`elif args.expectation_type == 'Column A Less Than Column B':
data_ge.expect_column_pair_values_a_to_be_greater_than_b(column_A=args.column_b, column_B=args.column, or_equal=args.or_equal, mostly=args.mostly, condition_parser='pandas', row_condition=args.row_condition)
```

**Environment (please complete the following information):**
 - Operating System: MacOS
Great expectations is being run through Databricks and imported within the notebook:
```
import great_expectations as ge
from great_expectations.core.batch import BatchRequest, RuntimeBatchRequest
from great_expectations.core.expectation_suite import ExpectationSuite
from great_expectations.core.expectation_configuration import ExpectationConfiguration
from great_expectations.data_context import BaseDataContext
from great_expectations.data_context.types.base import (
    DataContextConfig,
    FilesystemStoreBackendDefaults,
)
from great_expectations.profile.json_schema_profiler import JsonSchemaProfiler
from great_expectations.profile.user_configurable_profiler import UserConfigurableProfiler
from great_expectations.checkpoint import SimpleCheckpoint
```

**Comment by rdodev** [comment] 2022-10-28 20:10
Hey @grahamtyler 👋 

Very interesting issue/use case. Thanks for all the details. I will investigate and get back to you.

**Comment by rdodev** [comment] 2022-10-31 13:15
@grahamtyler 👋 

After some digging it would appear the issue is related to deprecated parts of our code not playing nice with newer parts of the code. `PandasDataset` is a V2 construct, and here's the way you should load the data in V3 data source:

* https://docs.greatexpectations.io/docs/guides/miscellaneous/how_to_quickly_explore_expectations_in_a_notebook/#1-import-great-expectations
* https://docs.greatexpectations.io/docs/tutorials/getting_started/tutorial_connect_to_data

**Comment by grahamtyler** [comment] 2022-10-31 17:09
@rdodev -- Thanks for looking into this! To make sure I understand, are you saying we _cannot_ load the data as a `PandasDataset` anymore with V3? 

We are using the process outlined in your first link (as far as I know): `data = pd.read_csv()` -> `data_ge = ge.from_pandas(data)` to load a CSV as a `PandasDataset`.

I'm not sure I fully follow what we should do from your second link if that approach no longer works in V3. We are running this in Databricks with the dataframe to validate being loaded as a CSV file (from FileStore). Seems like it should be straightforward to load that data without using CLI. 

Would using `SparkDFDataset` work for V3 instead of `PandasDataset`? Since we're using Databricks, I think that would work for us if needed and can test it out.

**Comment by rdodev** [comment] 2022-10-31 19:33
> To make sure I understand, are you saying we _cannot_ load the data as a `PandasDataset` anymore with V3?

You can, but it has to be defined as [V3 datasource](https://github.com/great-expectations/great_expectations/discussions/6252)

**Comment by grahamtyler** [comment] 2022-11-01 20:19
@rdodev -- Got it, I think I follow now. We are running everything in Databricks and followed the instructions [here](https://docs.greatexpectations.io/docs/deployment_patterns/how_to_use_great_expectations_in_databricks/) for setup. We are using "RuntimeDataConnector" when setting up the datasource. Relevant code is below on how we're loading the CSV from DBFS, creating data context, setting up datasource prior to the code above. I haven't been able to figure out what may be causing an issue, assuming that documentation for using GE in Databricks is up to date. 
 
Does anything look off to you on setting up the datasource? Is there a reason "RuntimeDataConnector" would not work for defining the dataframe as a V3 datasource? Do we need to set up the data context config before we read the CSV initially from DBFS?

-----

After installing GE, setting the file path:
**Load data** 
```
survey_fname = dbutils.widgets.get('Survey File Name')

survey = pd.read_csv(DATA_DIR_PYTHON + survey_fname)
```

Then **create data context**

```
def prepare_ge_context(root_dir: str) -> BaseDataContext:
    data_context_config = DataContextConfig(
        store_backend_defaults=FilesystemStoreBackendDefaults(
            root_directory=root_dir
        ),
    )
    ge_context = BaseDataContext(project_config=data_context_config)
    return ge_context

GE_DIR = ROOT_PYTHON + 'great_expectations/'
ge_context = prepare_ge_context(root_dir=GE_DIR)
```

Then **set up datasource**

```
def prepare_get_datasource() -> dict:
    ge_dataframe_datasource = {
        "name": DATA_SOURCE_NAME,
        "class_name": "Datasource",
        "execution_engine": {
        "module_name": "great_expectations.execution_engine",
        "class_name": "PandasExecutionEngine",
        },
        "data_connectors": {
            f"{DATA_SOURCE_NAME}_Data_Connector": {
                "module_name": "great_expectations.datasource.data_connector",
                "class_name": "RuntimeDataConnector",
                "batch_identifiers": [
                    "default_identifier_name"
                ],
            }
        },
    }
    return ge_dataframe_datasource

ge_context.add_datasource(**prepare_get_datasource())
```
We go on to set up a checkpoint and run the code above to load "survey" dataframe as a GE dataframe.

**Comment by grahamtyler** [comment] 2022-11-08 12:53
Hi @rdodev -- just following up to see if you have any ideas for where we might be going wrong in our setup of the environment and data source through databricks. As far as I can tell, this should work based on the documentation, but I'm obviously missing something. Thanks!

**Comment by rdodev** [comment] 2022-11-08 13:10
Hey @grahamtyler apologies for not asking earlier, is this running locally with data in databricks, or this running in databricks as spark job?

**Comment by grahamtyler** [comment] 2022-11-08 19:26
@rdodev -- we're using pandas for the checks and just using csv data uploaded to DBFS, so should be local to databricks and not a spark job.

**Comment by grahamtyler** [comment] 2022-11-15 02:51
Hi @rdodev -- just following up on this. Should we do something different based on whether this is local vs a spark job?

**Comment by roger-pharr** [comment] 2023-02-17 23:21
Hi all - Bumping this issue again: 

I see that the [PandasDataset expectation name](https://github.com/great-expectations/great_expectations/blob/b3b718e067e483483caab168722abb6279f00313/great_expectations/dataset/pandas_dataset.py#L1756) has different capitalization: `expect_column_pair_values_A_to_be_greater_than_B`, which must be why @grahamtyler and I were getting the not found error when we defined it.

Changing the name allows us  to add the expectation to our `DataSet`, but then when we run our checkpoint  we get another `ExpectationNotFoundError: expect_column_pair_values_A_to_be_greater_than_B not found`. Note the capitalization.

Should the name of this expectation in `PandasDataset` be changed?

**Comment by talagluck** [comment] 2023-03-12 14:32
Hi all - it seems there are two separate issues here. 

@grahamtyler - apologies for the delays. It is not clear what issue you are facing in your latest examples, but from my understanding, Databricks would typically be used with the SparkDFExecutionEngine rather than the PandasExecutionEngine, so it's possible there might be a cause there. If you are still having trouble here, could you please open a new Github Issue related to the issue you are facing on V3, and include the full stack trace?

@roger-pharr - thanks for bumping. As mentioned above, PandasDataset is from an older API which is soon to be deprecated. We would recommend following the flow in our docs, which should put you on the right path. We won't be making any changes to any of the Dataset classes at this time.

Thank you again for raising. I'm going to close this for now, but if you have additional questions, please don't hesitate to open a new Issue.

**Closed as not planned by talagluck** 2023-03-12 14:32 UTC
Labels: community, devrel
