### ISSUE TITLE
ConfigNotFoundError when instantiating DataContext with context_root_dir

### ISSUE THREAD

**Issue by paololucchino** [fivetran/great_expectations#5149] opened 2022-05-18 08:13 UTC
**Describe the bug**
The DataContext allows instantiating from a user-defined [context_root_dir](https://github.com/great-expectations/great_expectations/blob/5adf91121d49ce3144a1b4ccaa5ac58c00a99373/great_expectations/data_context/data_context/data_context.py#L314). The in-code documentation indicates this should be [the parent folder containing the great_expectations folder](https://github.com/great-expectations/great_expectations/blob/5adf91121d49ce3144a1b4ccaa5ac58c00a99373/great_expectations/data_context/data_context/data_context.py#L342)

However, [when constructing the path to the great_expectations.yaml file](https://github.com/great-expectations/great_expectations/blob/5adf91121d49ce3144a1b4ccaa5ac58c00a99373/great_expectations/data_context/data_context/data_context.py#L412)  the /great_expectations/ subfolder is not included in the path.

This leads to this error
```
ConfigNotFoundError: Error: No great_expectations directory was found here!
```

**To Reproduce**
```
from great_expectations.data_context.data_context import DataContext
ROOT_DIRECTORY = "YOUR_ROOT_PATH"
context = DataContext(context_root_dir=ROOT_DIRECTORY)
```

**Expected behavior**
We would expect the code above to instantiate a DataContext

Currently a successful work-around is:
```
context = DataContext(context_root_dir=f"{ROOT_DIRECTORY}/great_expectations/" )
```

**Environment (please complete the following information):**
 - Operating System: MacOS and AWS DataBricks
 - Great Expectations Version: 0.15.5

**Comment by austiezr** [comment] 2022-05-18 19:39
Hey @paololucchino ! Thanks for reaching out here. We're reviewing internally and will be in touch.

**Comment by talagluck** [comment] 2022-11-15 16:31
Hi @paololucchino - following up here, this does work as intended. We will update [the line in the code here](https://github.com/great-expectations/great_expectations/blob/5adf91121d49ce3144a1b4ccaa5ac58c00a99373/great_expectations/data_context/data_context/data_context.py#L342) to make that clearer. Thank you again for the feedback!

**Closed as completed** 2022-11-16 15:51 UTC
Labels: community, devrel
