### ISSUE TITLE
Failed airflow dag with lingering query still running in the database taking up resources

### ISSUE THREAD

**Issue by y-tee** [fivetran/great_expectations#2217] opened 2020-12-30 14:32 UTC
**Describe the bug**
I was trying to generate batch dataset from redshift on about 300mil rows of data for both expectation suite generation and validation using `context.build_batch_kwargs` and then `context.get_batch` in [code](https://github.com/y-tee/ge_tutorials/blob/e7fe33913c775619a3669515baff52abdba7e266/ge_dbt_airflow_tutorial/airflow/airflow_func.py#L29) on a 300 mil row data on redshift, 

which then fail with error:
```
[SQL: CREATE TEMPORARY TABLE "ge_tmp_0aa89f4b" AS SELECT * FROM ml_public.usertransaction_v3 WHERE '2019-06-01'::date <= transactiondate AND transactiondate <= '2020-06-01'::date;]
(Background on this error at: http://sqlalche.me/e/e3q8)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
psycopg2.OperationalError: SSL SYSCALL error: EOF detected
```

I run a few dags consecutively and showing me similar error, and the query from the failed dags like
```
CREATE TEMPORARY TABLE "ge_tmp_80939eb6" AS SELECT * FROM ml_public.usertransaction_v3 WHERE '2019-06-01'::date <= transactiondate AND transactiondate <= '2020-06-01'::date;
```
were still running in the background and causes table lock

**Expected behavior**
The queries should be terminated once dag fails. 
I did not know it was still running which then causes me to continue to run the subsequent dags which triggers even more queries which then result to a table lock

**Environment (please complete the following information):**
 - OS: MacOS catalina 
 - GE Version: 0.12.9
 
**Additional context**

**Comment by eugmandel** [comment] 2021-01-04 22:28
@y-tee Thank you for reporting this! I suspect it is a Redshift issue of long running queries continuing even after the client disconnectes. However, we will run some tests to verify that Great Expectations acts as a "well behaved client". We will post any updates in a comment on this issue.

**Comment by talagluck** [comment] 2021-02-03 19:17
Hi @y-tee! I have been looking into this, but I'm having trouble reproducing this. Could you confirm that this is still an issue with the latest GE version? If we come up with a fix, would you be available to test it? Thanks!

**Comment by talagluck** [comment] 2021-02-05 15:15
I was not able to reproduce this. I set up a redshift instance with 1 node, and tried several times to spike the system by making multiple queries at the same time while trying to instantiate a batch. The batch took a long time to instantiate, but did not fail in this way. I do suspect that this is a Redshift issue, rather than a GE issue, as I've personally had issues with Redshift taking a long time to clear queries which have been user terminated. I am closing this for now, but please feel free to re-open if this comes up again.

I did find a few references to keepalives arguments when creating the SQL alchemy engine (e.g. https://stackoverflow.com/questions/43594310/redshift-sqlalchemy-long-query-hangs#comment74248226_43594310). It seems like this has helped some users when facing this Redshift error. I believe the new Great Expectations API would enable us to pass these in as kwargs, so this could be a potential fix.

**Closed as completed by talagluck** 2021-02-05 15:15 UTC
