### ISSUE TITLE
Column Count Expectation getting killed

### ISSUE THREAD

**Issue by ps993w** [fivetran/great_expectations#5795] opened 2022-08-19 18:39 UTC
checkpoint with expectations as "expect_column_proportion_of_unique_values_to_be_between" or expect_column_unique_value_count_to_be_between is getting killed with no error msg. Expectation is running on SF table of ~ 2GB in size

**To Reproduce**
1. Go to expectation dir and create an expectation as

  "data_asset_type": null,
  "expectation_suite_name": "ID_BRIDGE",
  "expectations": [
   {
   "expectation_type": "expect_table_row_count_to_be_between",
      "kwargs": {
        "max_value": 700000000,
        "min_value": 1
      },
      "meta": {}
    },
   {
    "expectation_type": "expect_column_proportion_of_unique_values_to_be_between",
       "kwargs": {
         "column": "id",
	 "min_value": 1,
         "max_value": 4000000000,
	 "catch_exceptions": "True"
      },
      "meta": {}
    }
  ],
  "ge_cloud_id": null,
  "meta": {
    "great_expectations_version": "0.15.18"
  }
}

2. Create checkpoint - as
name: IDBRIDGE_CURRENT_FILTERED_CHKPNT
config_version: 1
class_name: Checkpoint
run_name_template: '%Y%m%d-%H%M%S-IDBRIDGE_CURRENT_FILTERED_template'
validations:
  - batch_request:
      datasource_name:  SF_DB
      data_connector_name: default_inferred_data_connector_name
      data_asset_name:<table_name>
    expectation_suite_name: ID_BRIDGE
    action_list:
      - name: store_validation_result
        action:
          class_name: StoreValidationResultAction
      - name: store_evaluation_params
        action:
          class_name: StoreEvaluationParametersAction
      - name: update_data_docs
        action:
          class_name: UpdateDataDocsAction
evaluation_parameters: {}
runtime_configuration:
  result_format:
    result_format: BASIC
    partial_unexpected_count: 20

4. Configure data source in great_expectations.yml file
5. Run check point and see the error
 great_expectations checkpoint run IDBRIDGE_CURRENT_FILTERED_CHKPNT
this is test
/home/ec2-user/airflowvenv/bin/great_expectations
Using v3 (Batch Request) API
Calculating Metrics:  40%|██████████████████████████████████████████████████████████████████████████▍                                                                                                               | 4/10 [00:01<00:01,  4.44it/s]Killed

**Expected behavior**

**Environment (please complete the following information):**
 - Operating System: EC2 Instance AMAZON LINUX
 - Great Expectations Version: 0.15.18

**Additional context**

**Comment by talagluck** [comment] 2022-08-22 14:10
Hi @ps993w - thank you very much for opening this issue. We are in the process of reviewing and will be in touch as we progress.

**Comment by billdirks** [comment] 2023-05-09 21:30
Hi @ps993w, 
Thanks for opening this issue. I am starting to look into it and have a few questions:

1. Have you successfully run this with a smaller table? Since your process is being killed by the OS, it seems likely that it may be due to a resource constraint on your EC2 instance. How big is your instance and have you monitored the memory usage of this process?

If it is still getting killed with a smaller data set could you answer the following questions:

1. What is an "SF" table? Is this a table name or a particular database type?
2. Could you provide you configuration file (removing any private keys) and a code snippet where you are hitting this issue?

**Comment by billdirks** [comment] 2023-05-19 18:13
I'm going to close this as I can't reproduce. If you are still seeing this @ps993w please feel free to re-open. Thanks.

**Closed as completed by billdirks** 2023-05-19 18:13 UTC
Labels: community, devrel
