### ISSUE TITLE
Exception in all column based expectations execution result after run_validation_operator when using dynamic query as expectation kwargs value_set $PARAMETER

### ISSUE THREAD

**Issue by amraf1002** [fivetran/great_expectations#3796] opened 2021-12-04 05:46 UTC
**Describe the bug**
According to Step 3 in [Dynamic Database Evaluation Parameters](https://docs.greatexpectations.io/docs/guides/expectations/advanced/how_to_dynamically_load_evaluation_parameters_from_a_database/#steps ), the urn must follow the structure, urn:great_expectations:stores:<query_store>:<query>. But after run_validation_operator excutes all column value based expectations returns exception in result summary even if only one expectation has dynamic query parameter.
#3660 
**To Reproduce**
1. Setup context with SqlAlchemyExecutionEngine for Bigquery and TupleGCSStoreBackend as Expectation & Validation & Datadocs store. Also setup querystore to load evaluation parameter from BQ. 
2. use RuntimeBatchRequest with "query" then context.get_validator
3. run context.run_validation_operator
4. check results, below is the exception traceback

**Expected behavior**
results with correct result summary

**Environment (please complete the following information):**
 - GCP Dataproc Debian
 - Great Expectations Version: latest develop branch v0.13.34

**Additional context**
"result": {},
"exception_info": {
"exception_traceback": "Traceback (most recent call last):\n File "/home/amitk_ghosh3/great_expectations-develop/great_expectations/execution_engine/execution_engine.py", line 377, in resolve_metrics\n **metric_provider_kwargs\n File "/home/amitk_ghosh3/great_expectations-develop/great_expectations/expectations/metrics/map_metric_provider.py", line 2049, in _sqlalchemy_column_map_condition_values\n for val in execution_engine.engine.execute(query).fetchall()\n File "", line 2, in execute\n File "/opt/conda/default/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 401, in warned\n return fn(*args, **kwargs)\n File "/opt/conda/default/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3139, in execute\n return connection.execute(statement, *multiparams, **params)\n File "/opt/conda/default/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1289, in execute\n return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)\n File "/opt/conda/default/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 326, in _execute_on_connection\n self, multiparams, params, execution_options\n File "/opt/conda/default/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1479, in _execute_clauseelement\n linting=self.dialect.compiler_linting | compiler.WARN_LINTING,\n File "/opt/conda/default/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 539, in _compile_w_cache\n **kw\n File "/opt/conda/default/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 555, in _compiler\n return dialect.statement_compiler(dialect, self, **kw)\n File "/opt/conda/default/lib/python3.7/site-packages/pybigquery/sqlalchemy_bigquery.py", line 222, in init\n super(BigQueryCompiler, self).init(dialect, statement, *args, **kwargs)\n File "/opt/conda/default/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 776, in init\n Compiled.init(self, dialect, statement, **kwargs)\n File "/opt/conda/default/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 451, in init\n self.string = self.process(self.statement, **compile_kwargs)\n File "/opt/conda/default/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 486, in process\n return obj._compiler_dispatch(self, **kwargs)\n File "/opt/conda/default/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch\n return meth(self, **kw)\n File "/opt/conda/default/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 3371, in visit_select\n kwargs,\n File "/opt/conda/default/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 3522, in _compose_select_body\n select._where_criteria, from_linter=from_linter, **kwargs\n File "/opt/conda/default/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 1662, in _generate_delimited_and_list\n return clauses[0]._compiler_dispatch(self, **kw)\n File "/opt/conda/default/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch\n return meth(self, **kw)\n File "/opt/conda/default/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 1681, in visit_clauselist\n return self._generate_delimited_list(clauselist.clauses, sep, **kw)\n File "/opt/conda/default/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 1649, in _generate_delimited_list\n for s in (c._compiler_dispatch(self, **kw) for c in elements)\n File "/opt/conda/default/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 1648, in \n s\n File "/opt/conda/default/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 1649, in \n for s in (c._compiler_dispatch(self, **kw) for c in elements)\n File "/opt/conda/default/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 82, in compiler_dispatch\n return meth(self, **kw)\n File "/opt/conda/default/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 2152, in visit_binary\n return disp(binary, operator, **kw)\n File "/opt/conda/default/lib/python3.7/site-packages/pybigquery/sqlalchemy_bigquery.py", line 325, in visit_not_in_op_binary\n + ")"\n File "/opt/conda/default/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 2219, in _generate_generic_binary\n self, eager_grouping=eager_grouping, **kw\n File "/opt/conda/default/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 82, in compiler_dispatch\n return meth(self, **kw)\n File "/opt/conda/default/lib/python3.7/site-packages/pybigquery/sqlalchemy_bigquery.py", line 437, in visit_bindparam\n assert(self.expanded_param(param), f"Unexpected param: {param}")\n File "/opt/conda/default/lib/python3.7/site-packages/pybigquery/sqlalchemy_bigquery.py", line 63, in assert\n raise AssertionError(message)\nAssertionError: Unexpected param: ([POSTCOMPILE_dml_type_1])\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n File "/home/amitk_ghosh3/great_expectations-develop/great_expectations/validator/validator.py", line 719, in resolve_validation_graph\n runtime_configuration=runtime_configuration,\n File "/home/amitk_ghosh3/great_expectations-develop/great_expectations/validator/validator.py", line 1633, in _resolve_metrics\n runtime_configuration=runtime_configuration,\n File "/home/amitk_ghosh3/great_expectations-develop/great_expectations/execution_engine/execution_engine.py", line 381, in resolve_metrics\n message=str(e), failed_metrics=(metric_to_resolve,)\ngreat_expectations.exceptions.exceptions.MetricResolutionError: Unexpected param: ([POSTCOMPILE_dml_type_1])\n",
"exception_message": "Unexpected param: (_[POSTCOMPILE_dml_type_1])",
"raised_exception": true
},

**Comment by cdkini** [comment] 2021-12-06 18:59
Hey @amraf1002! Thanks for opening this issue.

As we're advancing our codebase and overall library, we're actually moving away from validation operators. While they're not fully deprecated, their usage is not recommended with more recent version of GE.

Would you mind trying Checkpoints instead and seeing if that path works well?

**Comment by cdkini** [comment] 2021-12-28 15:47
@amraf1002 I'm going to go ahead and close this issue but please feel free to open a new one if the issue still persists. I believe Checkpoints are the supported path here so that should get you the intended behavior!

**Closed as completed by cdkini** 2021-12-28 15:47 UTC
Labels: community, devrel

**Comment by miike** [comment] 2022-02-03 06:54
Having hit this issue myself I believe the problem occurs on Linux when running with BigQuery and specific versions of SQL Alchemy and expectations that use value_sets (e.g., `expect_column_values_to_be_in_set`). We fixed this by explicitly pinning SQL Alchemy to `SQLAlchemy==1.4.25`
